---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: &app minio
  namespace: networking
  labels:
    app.kubernetes.io/name: *app
    app.kubernetes.io/instance: *app
spec:
  ingressClassName: nginx
  rules:
    - host: &host "minio.${DOMAIN}"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: *app
                port:
                  number: 9000
  tls:
    - hosts:
        - *host
---
apiVersion: v1
kind: Service
metadata:
  name: &app minio
  namespace: networking
  labels:
    app.kubernetes.io/name: *app
    app.kubernetes.io/instance: *app
spec:
  type: ExternalName
  externalName: s3.${HOMEDOMAIN}
  ports:
    - name: http
      port: 9000
      protocol: TCP
