---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: &app athena
  namespace: networking
  labels:
    app.kubernetes.io/name: *app
    app.kubernetes.io/instance: *app
#  annotations:
#    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
spec:
  ingressClassName: nginx-internal
  rules:
    - host: &host "athena.${DOMAIN}"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: *app
                port:
                  number: 5000
  tls:
    - hosts:
        - *host
---
apiVersion: v1
kind: Service
metadata:
  name: &app athena
  namespace: networking
  labels:
    app.kubernetes.io/name: *app
    app.kubernetes.io/instance: *app
spec:
  type: ExternalName
  externalName: nas.${HOMEDOMAIN}
  ports:
    - name: http
      port: 5000
      protocol: TCP
