---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: uptime-kuma-v1
  namespace: monitoring
  labels:
    app.kubernetes.io/name: &name uptime-kuma
    app.kubernetes.io/instance: *name
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: ceph-block