---
apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: uptime-kuma-backup
  namespace: monitoring
spec:
  sourcePVC: uptime-kuma-v1
  trigger:
    schedule: "0 22 * * *"
  restic:
    copyMethod: Snapshot
    pruneIntervalDays: 14
    storageClassName: ceph-block
    repository: uptime-kuma-restic-secret
    retain:
      daily: 14
---
apiVersion: v1
kind: Secret
metadata:
  name: uptime-kuma-restic-secret
  namespace: monitoring
type: Opaque
stringData:
  # The repository url
  RESTIC_REPOSITORY: s3:http://192.168.178.35:9000/uptime-kuma
  # The repository encryption key
  RESTIC_PASSWORD: "${RESTIC_PW}"
  # ENV vars specific to the back end
  # https://restic.readthedocs.io/en/stable/030_preparing_a_new_repo.html
  AWS_ACCESS_KEY_ID: "${MINIO_USER}"
  AWS_SECRET_ACCESS_KEY: "${MINIO_PASSWORD}"
