---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vaultwarden-v1
  namespace: default
  labels:
    app.kubernetes.io/name: &name vaultwarden
    app.kubernetes.io/instance: *name
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: ceph-block