---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: vaultwarden
  namespace: default
spec:
  interval: 5m
  chart:
    spec:
      chart: app-template
      version: 1.5.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s-charts
        namespace: flux-system
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    controller:
      type: statefulset
      annotations:
        reloader.stakater.com/auto: "true"
    image:
      # -- image repository
      repository: vaultwarden/server
      # -- image pull policy
      pullPolicy: IfNotPresent
      # -- image tag
      tag: 1.28.1

    strategy:
      type: Recreate

    # -- environment variables. See [image docs](https://github.com/dani-garcia/vaultwarden/blob/main/.env.template) for more details.
    # @default -- See below
    env:
    # -- Config dir
      DATA_FOLDER: "config"
      DOMAIN: https://vault.${DOMAIN}
      SIGNUPS_ALLOWED: "true"
      SMTP_FROM_NAME: Vaultwarden
      SMTP_HOST: mail.${SECRET_FAM_DOMAIN}
      SMTP_PORT: 587
      SMTP_SSL: "true"
      TZ: "Europe/Berlin"
      WEBSOCKET_ADDRESS: 0.0.0.0
    envFrom:
      - secretRef:
          name: vaultwarden
    # -- Configures service settings for the chart. Normally this does not need to be modified.
    # @default -- See values.yaml
    service:
      main:
        ports:
          http:
            port: 80
          websocket:
            enabled: true
            port: 3012

    ingress:
      # -- Enable and configure ingress settings for the chart under this key.
      # @default -- See values.yaml
      main:
        enabled: true
        ingressClassName: "nginx"
        annotations:
          cert-manager.io/cluster-issuer: "letsencrypt-production"  
        hosts:
          - host: "vault.${DOMAIN}"
            paths:
            - path: /
              pathType: Prefix
            - path: /notifications/hub
              pathType: Prefix
              service:
                port: 3012
            - path: /notifications/hub/negotiate
              pathType: Prefix
        tls:
          - hosts:
              - "vault.${DOMAIN}"
      admin:
        enabled: true
        ingressClassName: "nginx"
        annotations:
          nginx.ingress.kubernetes.io/whitelist-source-range: 10.0.0.0/8, 172.16.0.0/12, 192.168.0.0/16
        hosts:
          - host: "vault.${DOMAIN}"
            paths:
              - path: /admin
                pathType: Prefix
        tls:
          - hosts:
              - "vault.${DOMAIN}"
    persistence:
        config:
          enabled: true
          existingClaim: vaultwarden-v1
    resources:
      requests:
        cpu: 100m
        memory: 200Mi
      limits:
        cpu: 200m
        memory: 300Mi
