# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: vaultwarden
    namespace: default
stringData:
    ADMIN_TOKEN: ENC[AES256_GCM,data:mWJ2mvz4zW53Rbzi+7gCPUCNSZxxi0osdqsMadWfnOrlyMA9BVwztyCUDvmHbkU1z3sgjSxwiOnHE5tr+czJ8g==,iv:kushDULiWoDcnb7k/VptqGg6zZcthxZEJuGJ2xKM9D8=,tag:iahBfLjuIiaDtYomQBnBmw==,type:str]
    SMTP_FROM: ENC[AES256_GCM,data:EgriYYdwU3Fq1rCGvoqhYCqR9YaOFQaecQ1qgeQ=,iv:M1jjTZ8MjeH+ev60//Vl03HMSDoNVatXw/oaTiIregM=,tag:w61EdUi4WFEMe1A2u7cPrw==,type:str]
    SMTP_USERNAME: ENC[AES256_GCM,data:xbmMzjl6yoCWHPOQ1fkAaJvhqRo9Df59vOpOfw==,iv:rfqzrso0qkRJhAJ4RLKYEygYmVIBhuRJJhsJ3LtScd0=,tag:Ef4lZridcejqMs17RDlkeQ==,type:str]
    SMTP_PASSWORD: ENC[AES256_GCM,data:13i7ClVaAARsmlWcsfBsPsOgyaHK,iv:IBCJftNgDqfZvxqY5cscnGO1o8ZhKMd7SJVButQwyDI=,tag:UGHNGM8Yeu9+D3RZMLXepw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age14zezx8350dxxh9kpqhpcna7a3gsma24n63qppqy0vfq47vvfkatqry5e9q
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4Y2V2REtFN0ZuWTE4Zkg5
            VHlVRnJDOXVxR3IvSElVREZCSXlGbnpyZ25BCklMUWJQR2s5c3ViNGE3YWpYS2hv
            c1ZuaVl2d2NXeldsVTZKRHFkWHpmZGMKLS0tIGdoMGZGUVJnNVloVFVZRzRWeWRN
            MHI3WU5uTmY1MWhoYVo1eFNiUGdwSnMK2MhgaGBwTqmkPheQQzg+GlyOrT+XjALX
            HBM+cRMX0Ae7VW1IoYX2dcSW9P/+kt7oyb/AFjMt4UzEtrOcNkNRVw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-03-04T22:01:04Z"
    mac: ENC[AES256_GCM,data:KOD7KEtEvN73EZbjBxupGSAAHmvb4nFmOBrWh0N9UOQipHFtrKN1+J93g7H5tKUt6+FUHZobfmxaKcuBe/baMc0TChjvASreY1OYLufFzNCgm+dTB7bkTvZmb+FB+ygS0exDVHCS9jiKNDDUH8VEtsaGitDpPAhczXyfxDmMsWM=,iv:hRRz1/JE5YMHwZPkzKoV/iaRBeI7sGWANgnAec2pjcw=,tag:5QsYGdCq0gFuL97SAdvlyA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
