---
apiVersion: volsync.backube/v1alpha1
kind: ReplicationDestination
metadata:
  name: vaultwarden-restic-restore
  namespace: home
spec:
  trigger:
    manual: restore-once
  restic:
    destinationPVC: vaultwarden-v2
    repository: vaultwarden-restic
    copyMethod: Direct
---
apiVersion: v1
kind: Secret
metadata:
  name: vaultwarden-restic
  namespace: home
type: Opaque
stringData:
  # The repository url
  RESTIC_REPOSITORY: s3:http://minio.storage.svc.cluster.local:9000/vaultwarden-restic
  # The repository encryption key
  RESTIC_PASSWORD: "${RESTIC_PW}"
  # ENV vars specific to the back end
  # https://restic.readthedocs.io/en/stable/030_preparing_a_new_repo.html
  AWS_ACCESS_KEY_ID: "${MINIO_USER}"
  AWS_SECRET_ACCESS_KEY: "${MINIO_PASSWORD}"
