---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: default
resources:
  - ./helmrelease.yaml
  - ./volsync.yaml
  - ./volsync_external.yaml
  - ./pvc.yaml
labels:
  - pairs:
      app.kubernetes.io/name: freshrss
      app.kubernetes.io/instance: freshrss