---
apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: freshrss-backup-external
  namespace: default
spec:
  sourcePVC: freshrss-config-v1
  trigger:
    schedule: "0 22 * * *"
  restic:
    copyMethod: Snapshot
    pruneIntervalDays: 14
    repository: freshrss-restic-secret-external
    retain:
      daily: 14
---
apiVersion: v1
kind: Secret
metadata:
  name: freshrss-restic-secret-external
  namespace: default
type: Opaque
stringData:
  # The repository url
  RESTIC_REPOSITORY: s3:https://s3api.nosync.eu/nao
  # The repository encryption key
  RESTIC_PASSWORD: "${RESTIC_PW}"
  # ENV vars specific to the back end
  # https://restic.readthedocs.io/en/stable/030_preparing_a_new_repo.html
  AWS_ACCESS_KEY_ID: "${CK_ACCESS_KEY}"
  AWS_SECRET_ACCESS_KEY: "${CK_SECRET_KEY}"