---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: jellyfin
  namespace: default
spec:
  interval: 5m
  chart:
    spec:
      chart: app-template
      version: 1.5.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s-charts
        namespace: flux-system
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    controller:
      type: statefulset
      annotations:
        reloader.stakater.com/auto: "true"
    image:
      repository: jellyfin/jellyfin
      tag: 10.8.10
      pullPolicy: IfNotPresent
    env:
      TZ: ${TIMEZONE}
      JELLYFIN_CACHE_DIR: "/config/cache"
    service:
      main:
        ports:
          http:
            port: &port 8096
    ingress:
      main:
        enabled: true
        ingressClassName: "nginx"
        annotations:
          cert-manager.io/cluster-issuer: "letsencrypt-production"
          nginx.ingress.kubernetes.io/whitelist-source-range: |
            10.0.0.0/8,172.16.0.0/12,192.168.0.0/16
        hosts:
          - host: "jelly.${DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
        - hosts:
            - "jelly.${DOMAIN}"
    persistence:
      transcode:
        enabled: true
        type: emptyDir
      config:
        enabled: true
        existingClaim: jellyfin-config-v1
        mountPath: /config
      # Cache does NOT contain temporary transcoding data.
      media:
        enabled: true
        type: custom
        volumeSpec:
          nfs:
            server: 192.168.178.35
            path: /volume1/media/Video
        mountPath: /media
        readOnly: false
    podSecurityContext: 
      supplementalGroups: [44, 109, 10000]
    nodeSelector:
      intel.feature.node.kubernetes.io/gpu: "true"
    resources:
      requests:
        gpu.intel.com/i915: 1
        cpu: 100m
        memory: 1000Mi
      limits:
        gpu.intel.com/i915: 1
        memory: 4000Mi
    probes:
      liveness: &probes
        enabled: true
        custom: true
        spec:
          httpGet:
            path: /health
            port: *port
          initialDelaySeconds: 0
          periodSeconds: 10
          timeoutSeconds: 1
          failureThreshold: 3