---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: k8s-gateway
  namespace: networking
spec:
  interval: 10m
  chart:
    spec:
      chart: k8s-gateway
      version: 2.0.4
      sourceRef:
        kind: HelmRepository
        name: k8s-gateway
        namespace: flux-system
  maxHistory: 3
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    image:
      registry: quay.io
      repository: oriedge/k8s_gateway
      tag: v0.3.4
    replicaCount: 2
    domain: ${DOMAIN}
    ttl: 30
    service:
      type: LoadBalancer
      port: 53
      annotations:
        metallb.universe.tf/loadBalancerIPs: "${GATEWAY_DNS_LB}"
      externalTrafficPolicy: Local
    resources:
      requests:
        cpu: 10m
        memory: 30Mi
      limits:
        memory: 50Mi
    extraZonePlugins:
      - name: log
      - name: errors
      - name: health
        configBlock: |-
          lameduck 5s
      - name: ready
      - name: prometheus
        parameters: 0.0.0.0:9153
      - name: forward
        parameters: ". 192.168.178.5:53"
      - name: loop
      - name: reload
      - name: loadbalance