---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: harbor
  namespace: default
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://helm.goharbor.io
      chart: harbor
      version: 1.11.0
      sourceRef:
        kind: HelmRepository
        name: goharbor
        namespace: flux-system
  values:
    expose:
      type: ingress
      tls:
        # The ingress controller has a default certificate so we don't need to configure it
        certSource: none
      # Default Values
      ClusterIP:
        name: harbor
        ports:
          httpPort: 80
          httpsPort: 443
      ingress:
        hosts:
          core: registry.${DOMAIN}
        annotations:
          nginx.ingress.kubernetes.io/proxy-body-size: "0"
          nginx.ingress.kubernetes.io/proxy-connect-timeout: "480"
          nginx.ingress.kubernetes.io/custom-http-errors: "418"
    externalURL: https://registry.${DOMAIN}
    secretKey: "${HARBOR_SECRET_KEY}"
    harborAdminPassword: "${HARBOR_ADMIN_PASSWORD}"
    notary:
      enabled: false
    persistence:
      enabled: true
      resourcePolicy: "keep"
      persistentVolumeClaim:
        registry:
          storageClass: ceph-block
          size: 50Gi
        chartmuseum:
          storageClass: ceph-block
          size: 5Gi
        jobservice:
          jobLog:
            storageClass: ceph-block
            size: 5Gi
          scanDataExports:
            storageClass: ceph-block
            size: 5Gi
        redis:
          storageClass: ceph-block
          size: 5Gi
        trivy:
          storageClass: ceph-block
          size: 5Gi
    redis:
      type: internal
#    database:
#      type: internal
#      internal:
#        password: "${HARBOR_POSTGRES_PASSWORD}"
    database:
      type: external
      external:
        host: "postgres-harbor-rw.harbor.svc"
        port: "5432"
        username: "harbor"
        existingSecret: "cnpg-harbor-secret"
        coreDatabase: "registry"
