---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-home-assistant
  namespace: flux-system
spec:
  path: ./kubernetes/apps/home-automation/home-assistant/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-ops-kubernetes
  wait: true
  interval: 10m
  dependsOn:
    - name: cluster-apps-rook-ceph-cluster
    - name: cluster-apps-volsync
