---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: paperless-redis
  namespace: default
spec:
  interval: 5m
  chart:
    spec:
      chart: redis
      version: 17.8.2
      sourceRef:
        kind: HelmRepository
        name: bitnami-charts
        namespace: flux-system
      interval: 5m
  values:
    architecture: standalone
    master:
      persistence:
        enabled: false
    metrics:
      enabled: false
      serviceMonitor:
        enabled: false
    auth:
      enabled: false