---
# yaml-language-server: $schema=https://raw.githubusercontent.com/JJGadgets/flux2-schemas/main/helmrelease-helm-v2beta1.json
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app mosquitto
  namespace: default
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 1.5.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s-charts
        namespace: flux-system
      interval: 15m
  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  values:
    controller:
      type: statefulset
      annotations:
        reloader.stakater.com/auto: "true"
    image:
      repository: public.ecr.aws/docker/library/eclipse-mosquitto
      tag: 2.0.18
    podAnnotations:
      reloader.stakater.com/auto: "true"
    service:
      main:
        type: LoadBalancer
        ports:
          http:
            enabled: false
          mqtt:
            enabled: true
            primary: true
            port: 1883
            protocol: TCP
        externalTrafficPolicy: Local
        annotations:
          io.cilium/lb-ipam-ips: 192.168.178.241
          coredns.io/hostname: "mqtt.${DOMAIN}"
    podSecurityContext:
      runAsUser: 3000
      runAsGroup: 3000
      fsGroup: 3000
      fsGroupChangePolicy: OnRootMismatch
    persistence:
      config:
        enabled: true
        type: configMap
        name: mosquitto-config
        mountPath: /mosquitto/config/mosquitto.conf
        subPath: mosquitto.conf
      data:
        enabled: true
        existingClaim: mosquitto-data-v1
        mountPath: /mosquitto/data
    resources:
      requests:
        cpu: 15m
        memory: 105Mi
      limits:
        memory: 105Mi
