---
apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: mosquitto-backup
  namespace: default
spec:
  sourcePVC: mosquitto-data-v1
  trigger:
    schedule: "0 22 * * *"
  restic:
    copyMethod: Snapshot
    pruneIntervalDays: 10
    repository: mosquitto-restic-secret
    retain:
      daily: 10
      within: 3d
---
apiVersion: v1
kind: Secret
metadata:
  name: mosquitto-restic-secret
  namespace: default
type: Opaque
stringData:
  # The repository url
  RESTIC_REPOSITORY: s3:http://minio.storage.svc.cluster.local:9000/mosquitto
  # The repository encryption key
  RESTIC_PASSWORD: "${RESTIC_PW}"
  # ENV vars specific to the back end
  # https://restic.readthedocs.io/en/stable/030_preparing_a_new_repo.html
  AWS_ACCESS_KEY_ID: "${MINIO_USER}"
  AWS_SECRET_ACCESS_KEY: "${MINIO_PASSWORD}"
