---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: nfs-csi
provisioner: nfs.csi.k8s.io
parameters:
  server: "${NEW_NFS_SERVER}"
  share: /mnt/k8s/PVCs
reclaimPolicy: Delete
volumeBindingMode: Immediate
mountOptions:
  - nfsvers=4.1
  - nconnect=8
  - hard
  - noatime

Alexander leo