apiVersion: v1
kind: Secret
metadata:
  name: vaultwarden-v1-backup
  namespace: home
type: Opaque
stringData:
  # The repository url
  RESTIC_REPOSITORY: s3:https://s3.int.swalb.io/vaultwarden-restic
  # The repository encryption key
  RESTIC_PASSWORD: test
  # ENV vars specific to the chosen back end
  # https://restic.readthedocs.io/en/stable/030_preparing_a_new_repo.html
  AWS_ACCESS_KEY_ID: "${MINIO_USER}"
  AWS_SECRET_ACCESS_KEY: "${MINIO_PASSWORD}"