---
creation_rules:
  - path_regex: kubernetes/.*\.sops\.ya?ml
    encrypted_regex: "^(data|stringData)$"
    key_groups:
      - age:
          - age14zezx8350dxxh9kpqhpcna7a3gsma24n63qppqy0vfq47vvfkatqry5e9q
  - path_regex: kubernetes/.*\.sops\.ini
    key_groups:
      - age:
          - age14zezx8350dxxh9kpqhpcna7a3gsma24n63qppqy0vfq47vvfkatqry5e9q
  - path_regex: kubernetes/.*\.sops\.toml
    key_groups:
      - age:
          - age14zezx8350dxxh9kpqhpcna7a3gsma24n63qppqy0vfq47vvfkatqry5e9q
  - path_regex: kubernetes/.*\.sops\.json
    key_groups:
      - age:
          - age14zezx8350dxxh9kpqhpcna7a3gsma24n63qppqy0vfq47vvfkatqry5e9q
  - path_regex: ansible/.*\.sops\.ya?ml
    key_groups:
      - age:
          - age14zezx8350dxxh9kpqhpcna7a3gsma24n63qppqy0vfq47vvfkatqry5e9q
  - path_regex: terraform/.*\.sops\.ya?ml
    key_groups:
      - age:
          - age14zezx8350dxxh9kpqhpcna7a3gsma24n63qppqy0vfq47vvfkatqry5e9q