---
creation_rules:
  - path_regex: kubernetes/.*\.sops\.ya?ml
    encrypted_regex: "^(data|stringData)$"
    key_groups:
      - age:
          - age1ce6neraa02llughs9qcw75u0jr9avef64fy2zln7vy8qu98mky2qxm59ju
  - path_regex: kubernetes/.*\.sops\.ini
    key_groups:
      - age:
          - age1ce6neraa02llughs9qcw75u0jr9avef64fy2zln7vy8qu98mky2qxm59ju
  - path_regex: kubernetes/.*\.sops\.toml
    key_groups:
      - age:
          - age1ce6neraa02llughs9qcw75u0jr9avef64fy2zln7vy8qu98mky2qxm59ju
  - path_regex: kubernetes/.*\.sops\.json
    key_groups:
      - age:
          - age1ce6neraa02llughs9qcw75u0jr9avef64fy2zln7vy8qu98mky2qxm59ju
  - path_regex: ansible/.*\.sops\.ya?ml
    key_groups:
      - age:
          - age1ce6neraa02llughs9qcw75u0jr9avef64fy2zln7vy8qu98mky2qxm59ju
  - path_regex: terraform/.*\.sops\.ya?ml
    key_groups:
      - age:
          - age1ce6neraa02llughs9qcw75u0jr9avef64fy2zln7vy8qu98mky2qxm59ju