---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-vaultwarden
  namespace: flux-system
spec:
  path: ./kubernetes/apps/security/vaultwarden/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-ops-kubernetes
  wait: true
  interval: 10m
  dependsOn:
    - name: cluster-apps-volsync
    - name: cluster-apps-rook-ceph-cluster
