---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kured
  namespace: kube-system
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://kubereboot.github.io/charts
      chart: kured
      version: 5.2.0
      sourceRef:
        kind: HelmRepository
        name: weaveworks-kured-charts
        namespace: flux-system
      interval: 5m
  values:
    updateStrategy: RollingUpdate
    configuration:
      startTime: "21am"
      endTime: "11am"
      logFormat: "json"
      timeZone: "Europe/Berlin"
#      rebootSentinelCommand: |-
#        sh -c "! needs-restarting --reboothint"
    tolerations:
      - key: node-role.kubernetes.io/master
        operator: Exists
        effect: NoSchedule
    metrics:
      create: true
