---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-mosquitto-app
  namespace: flux-system
spec:
  path: './kubernetes/apps/default/mosquitto/app'
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-ops-kubernetes
  wait: true
  interval: 10m
  dependsOn:
    - name: cluster-apps-rook-ceph-cluster
    - name: cluster-apps-volsync
