---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: databases
resources:
  - ./helmrelease.yaml
configMapGenerator:
  - name: cloudnative-pg-dashboard
    files:
      - cloudnative-pg-dashboard.json=https://raw.githubusercontent.com/cloudnative-pg/cloudnative-pg/main/docs/src/samples/monitoring/grafana-dashboard.json
generatorOptions:
  disableNameSuffixHash: true
  labels:
    grafana_dashboard: "true"
labels:
  - pairs:
      app.kubernetes.io/name: cnpg
      app.kubernetes.io/instance: cnpg
