# yamllint disable
apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: cloudnative-pg
    namespace: databases
stringData:
    username: ENC[AES256_GCM,data:iawKnH8=,iv:u7QQNqWi5dvYs0yi7fFLcAeo+WuA/Gq/blJsXXtPH6I=,tag:/++DlB50KibarNC5Kp9srQ==,type:str]
    password: ENC[AES256_GCM,data:BodN9bXluOTfCT/G,iv:lI3AnkWcKhnFNAdFLvdIdoEYYMCNPsialtdN2vSVRro=,tag:RaZHnoLMTf8zd9JbhMvnVg==,type:str]
    MINIO_SECRET_KEY: ENC[AES256_GCM,data:Ihpy1Xs1dqk=,iv:Jy3c6/zoSGmCtGn8gnMRKDuXcVKK0N2aj5FVCKFNRlA=,tag:Clr7KXtXu6/n7EnH/n94QA==,type:str]
    MINIO_ACCESS_KEY: ENC[AES256_GCM,data:/GC4sgTHqLP5cM0eMGRjdce8HEYU9dPRfZY=,iv:Bv3wnWPPQ5yYnjdcE5GQ4eRvTsz0NmSXKsgJqJRq82Q=,tag:d+BXTVdFPw9y5M+VPcHLyQ==,type:str]
