---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-reloader
  namespace: flux-system
spec:
  path: ./kubernetes/apps/kube-system/reloader/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-ops-kubernetes
  wait: false
  interval: 10m
