---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: hajimari
  namespace: home
spec:
  interval: 15m
  chart:
    spec:
      # renovate: registryUrl=https://hajimari.io
      chart: hajimari
      version: 1.2.0
      sourceRef:
        kind: HelmRepository
        name: hajimari-charts
        namespace: flux-system
      interval: 15m
  values:
    image:
      repository: ghcr.io/toboshii/hajimari
      tag: v0.2.0
    env:
      TZ: $"{TZ}""
    hajimari:
      defaultEnable: false
      namespaceSelector:
        matchNames:
          - kube-system
          - home
          - monitoring
          - networking
          - security
      name: "Sparks"
      customApps:
        - name: Habitica
          url: https://habitica.com
          icon: "check-bold"
      groups:
        - name: Kubernetes
          links:
            - name: SparksD2145/flux-infra
              url: "https://github.com/alb-dev/home-ops"
            - name: k8s-at-home Charts
              url: "https://github.com/k8s-at-home/charts/tree/master/charts"
        - name: Services
          links:
            - name: Cloudflare
              url: "https://dash.cloudflare.com"
            - name: Hetzner
              url: "https://hetzner.de"
        - name: Finance
          links:
            - name: PayPal
              url: "https://paypal.com"
        - name: Shopping
          links:
            - name: eBay
              url: "https://ebay.com/"
            - name: amazon
              url: "https://amazon.de/"
        - name: Media
          links:
            - name: YouTube
              url: "https://youtube.com/"
    ingress:
      main:
        enabled: true
        ingressClassName: "nginx"
        annotations:
          cert-manager.io/cluster-issuer: "letsencrypt-production"
        hosts:
          - host: "hajimari.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
        - hosts:
            - "hajimari.${SECRET_DOMAIN}"
          secretName: "hajimari.${SECRET_DOMAIN}"
    podAnnotations:
      configmap.reloader.stakater.com/reload: "hajimari-settings"
    resources:
      requests:
        cpu: 100m
        memory: 128M
