cluster:
  name: "home"
  id: "0"
rollOutCiliumPods: true
localRedirectPolicy: true
kubeProxyReplacement: "strict"
kubeProxyReplacementHealthzBindAddr: 0.0.0.0:10256
ipv4NativeRoutingCIDR: 10.43.0.0/16
k8sServiceHost: "192.168.178.210"
k8sServicePort: 6443
loadBalancer:
  algorithm: "maglev"
  mode: "dsr"
tunnel: "disabled"
autoDirectNodeRoutes: true
endpointRoutes:
  enabled: true
ipam:
  mode: "kubernetes"
operator:
  rollOutPods: true
  replicas: 3
  prometheus:
    enabled: false
    serviceMonitor:
      enabled: true
prometheus:
  enabled: false
  serviceMonitor:
    enabled: true
proxy:
  prometheus:
    enabled: true
containerRuntime:
  integration: containerd
hubble:
  enabled: true
  serviceMonitor:
    enabled: false
  metrics:
    enabled:
      - dns:query;ignoreAAAA
      - drop
      - tcp
      - flow
      - port-distribution
      - icmp
      - http
  relay:
    enabled: true
    rollOutPods: true
  ui:
    enabled: true
    rollOutPods: true
    ingress:
      enabled: true
      ingressClassName: "nginx"
      annotations:
        hajimari.io/enable: "true"
        hajimari.io/appName: hubble
        hajimari.io/icon: lan
      hosts:
        - &host "hubble.int.swalb.io"
      tls:
        - hosts:
            - *host
bgp:
  enabled: false
externalIPs:
  enabled: false
securityContext:
  privileged: true