apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
configMapGenerator:
  - name: synoglogy_dashboard
    files:
      - synoglogy_dashboard.json=./dashboards/synology_sashboard.json
generatorOptions:
  disableNameSuffixHash: true
  annotations:
    kustomize.toolkit.fluxcd.io/substitute: disabled
  labels:
    grafana_dashboard: "true"
resources:
  - prometheus
  - node-problem-detector
  - uptime-kuma
  - grafana
  - kubernetes-dashboard
  - snmp-exporter-synology

