# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: vaultwarden-secret
    namespace: security
stringData:
    ADMIN_TOKEN: ENC[AES256_GCM,data:mWJ2mvz4zW53Rbzi+7gCPUCNSZxxi0osdqsMadWfnOrlyMA9BVwztyCUDvmHbkU1z3sgjSxwiOnHE5tr+czJ8g==,iv:kushDULiWoDcnb7k/VptqGg6zZcthxZEJuGJ2xKM9D8=,tag:iahBfLjuIiaDtYomQBnBmw==,type:str]
    SMTP_FROM: ENC[AES256_GCM,data:PSDdqkosA8/gQkEMVPy4keY/Ji0H7hVH2nw=,iv:F1vczW0h3CIJzLjnfsZ36DfkAij8J6iW43CsZo10PUU=,tag:V7uy3ijMQm7upLhHn2Yb4w==,type:str]
    SMTP_USERNAME: ENC[AES256_GCM,data:jHQcjmy+YcX6ZMfwNtZlhXlllAOIHHtYqMRc4g==,iv:FKeCT1wmI243tZDYlSYUdUsv1xDFSX5Gn0KTXP5NLOM=,tag:VSOTvDM9oi0qh7YuTfUkvA==,type:str]
    SMTP_PASSWORD: ENC[AES256_GCM,data:Pttm0iSpkVcFi/LSgl6zQhEApI0iv21sa22P2lYkF2QArFxNfA==,iv:XZkqdhxS6Kneti3RRmOFQtQh8nhikLehbxlu8Qdjb0w=,tag:mpGDqPWbpxXrAEPjOjBggw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age14zezx8350dxxh9kpqhpcna7a3gsma24n63qppqy0vfq47vvfkatqry5e9q
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4Y2V2REtFN0ZuWTE4Zkg5
            VHlVRnJDOXVxR3IvSElVREZCSXlGbnpyZ25BCklMUWJQR2s5c3ViNGE3YWpYS2hv
            c1ZuaVl2d2NXeldsVTZKRHFkWHpmZGMKLS0tIGdoMGZGUVJnNVloVFVZRzRWeWRN
            MHI3WU5uTmY1MWhoYVo1eFNiUGdwSnMK2MhgaGBwTqmkPheQQzg+GlyOrT+XjALX
            HBM+cRMX0Ae7VW1IoYX2dcSW9P/+kt7oyb/AFjMt4UzEtrOcNkNRVw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-11-26T22:43:07Z"
    mac: ENC[AES256_GCM,data:z4r0tYYFAZ1ZtOmNf9CN7dOYk0723gVCjdW6xBrGwTELfd+AWVdkbPWHmAePQSo8mpKFwuUk9eSOcttLfPmNEV6qRUSDpKlCqstMSur2Ryf+u5HqVKlO9R6Z0sfXcpkWN/XbXhaRCKrLC6oQkLTOgQEqFMjQGcTz2uMIS4JDN9A=,iv:XKTakhl7mk3f3A+3LeXulkZxlgJbjcFpPLwrb+UkkGE=,tag:NjTTt2is2YHXv9fuwlYrew==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
