---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nextcloud-config-v1
  namespace: default
  labels:
    app.kubernetes.io/name: &name nextcloud
    app.kubernetes.io/instance: *name
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  storageClassName: ceph-filesystem
