---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: default
resources:
  - ./helmrelease.yaml
  - ./volsync.yaml
  - ./database/cluster.yaml
  - ./secret.sops.yaml
  - ./pvc.yaml
labels:
  - pairs:
      app.kubernetes.io/name: nextcloud
      app.kubernetes.io/instance: nextcloud
