---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nextcloud-nfs-config
spec:
  storageClassName: nextcloud-nfs-config
  capacity:
    storage: 1Mi
  accessModes:
    - ReadWriteMany
  nfs:
    server: "${NFS_SERVER}"
    path: /volume1/kubernetes/nextcloud
  mountOptions:
    - nfsvers=4.1
    - nconnect=16
    - tcp
    - intr
    - hard
    - noatime
    - nodiratime
    - rsize=1048576
    - wsize=1048576
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nextcloud-nfs-config
  namespace: default
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nextcloud-nfs-config
  resources:
    requests:
      storage: 1Mi
