apiVersion: v1
kind: Secret
metadata:
    name: nextcloud-secret
    namespace: default
stringData:
    nextcloud-username: ENC[AES256_GCM,data:gyFUDz+EXIn/Ne+90fI=,iv:xgTMoT/kRwG37/s+2pZ3CfgXuK4PF0sWpuHjBVM5INQ=,tag:WETKn81rxHb2irVJyHCtNQ==,type:str]
    nextcloud-password: ENC[AES256_GCM,data:ixF7mqWWhjywWO1OS+yr+FayeVabbtUoZQ==,iv:C4sUUqpREc9BbYhZcbuFBUhHItf5axphndYhDEf1fM0=,tag:UlX5CQOsvFTr2aUmStPVlg==,type:str]
    REDIS_PASSWORD: ENC[AES256_GCM,data:A+pskbtKlZsBqT0jDaRvRFGI/NDWXhNakA==,iv:JE1nR1dhdIFxyxbBhlqdetjgB3ZezWfuACEzKzWKW0w=,tag:RqJ+yVhIgwtSCEOn4CNXPw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age14zezx8350dxxh9kpqhpcna7a3gsma24n63qppqy0vfq47vvfkatqry5e9q
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzN2taamJZOVRLRVhRbWtk
            b1hXM2xoTm9hTmswOURZNEtJL2pPMzBnTFNFCkJhOWpMNzBFZWtuNTc1Q1pFSTgw
            eEdGQitmVCtSb0cvei9oWEQ2Z2tnVFUKLS0tIDdpc2JlakVuNlZCQnp1ZVRiQjNu
            Ti9oYjIwSXhRVEF0NEZpYXRXdjhpNGMKWxTAtU2HN0x0xCf47zmje03qwDSf/8Rl
            Z9afx76shY7r+dgit6eEAS/9Vv8oZ/zzUrjmrYn5i0jZoGU/gY21qw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-07-29T14:36:33Z"
    mac: ENC[AES256_GCM,data:N7K2THWSn//CpaGgr7DwEPCTYdPZl8G4OHFCsYPkJNzz9n4KL7rvBeSgS2Gq2GHwAqRRrqwnFaRp/Sd/kf7orbhdRURnyKzATr3WU2m6wVvV1jeYHP1jg+UzS2om8S1Sk6b2gCyWOfG4V4RC9O5lsz2YedmvZ3Efa8Ky978gHjE=,iv:aubA5TMolNVLlykSvmA2o0odFGqanDh5iH3aRBb8aSE=,tag:Tv7s0m/WmVaeLZ30pn5NJA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
