---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: jellyseerr
  namespace: home
  labels:
    component.kutara.io/part-of: standard-helm-release
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 1.3.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s-charts
        namespace: flux-system
  values:
    image:
      repository: docker.io/fallenbagel/jellyseerr
      tag: 1.4.1
    env:
      TZ: "Europe/Berlin"
      LOG_LEVEL: "info"
    service:
      main:
        ports:
          http:
            port: 5055
    ingress:
      main:
        enabled: true
        ingressClassName: "nginx"
        annotations:
          cert-manager.io/cluster-issuer: letsencrypt-production
          nginx.ingress.kubernetes.io/proxy-send-timeout: "600"
          nginx.ingress.kubernetes.io/proxy-connect-timeout: "600"
          nginx.ingress.kubernetes.io/proxy-read-timeout: "1800"
        hosts:
          - host: "request.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - secretName: jellyseerr-tls
            hosts:
              - request.${SECRET_DOMAIN}
    podSecurityContext:
      runAsUser: 568
      runAsGroup: 568
      fsGroup: 568
      fsGroupChangePolicy: "OnRootMismatch"
    persistence:
      config:
        enabled: true
        existingClaim: jellyseerr-config-v1
        mountPath: /app/config
    resources:
      requests:
        cpu: 10m
        memory: 50Mi
      limits:
        memory: 300Mi
        cpu: 200m