apiVersion: v1
kind: Secret
metadata:
  name: pgo-s3-creds
  namespace: home-automation
stringData:
  s3.conf: |
    [global]
    repo1-s3-key="${MINIO_USER}"
    repo1-s3-key-secret="${MINIO_PASSWORD}"