---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: mosquitto
  namespace: home-automation
spec:
  interval: 5m
  chart:
    spec:
      chart: app-template
      version: 2.3.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s-charts
        namespace: flux-system
      interval: 5m
  values:
    controllers:
      main:
        type: statefulset
        annotations:
          reloader.stakater.com/auto: "true"

        pod:
          securityContext:
            runAsUser: 2700
            runAsGroup: 2700
            fsGroup: 2700
            fsGroupChangePolicy: OnRootMismatch

        statefulset:
          volumeClaimTemplates:
            - name: config
              accessMode: ReadWriteOnce
              size: 1Gi
              storageClass: ceph-block
              globalMounts:
                - path: /data

        containers:
          main:
            image:
              repository: public.ecr.aws/docker/library/eclipse-mosquitto
              tag: 2.0.18
            resources:
              requests:
                cpu: 15m
                memory: 105Mi
              limits:
                memory: 105Mi

    service:
      main:
        type: LoadBalancer
        annotations:
          io.cilium/lb-ipam-ips: "192.168.178.241"
        externalTrafficPolicy: Cluster
        ports:
          http:
            enabled: false
          mqtt:
            enabled: true
            port: 1883

    configMaps:
      config:
        enabled: true
        data:
          mosquitto.conf: |
            per_listener_settings false
            listener 1883
            allow_anonymous true
            persistence true
            persistence_location /data/mosquitto/
            autosave_interval 1800
            connection_messages true
            autosave_interval 60

    persistence:
      config:
        enabled: true
        type: configMap
        name: mosquitto-config
        globalMounts:
          - path: /mosquitto/config/mosquitto.conf
            subPath: mosquitto.conf
