# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: grafana-secret
    namespace: monitoring
stringData:
    admin-user: ENC[AES256_GCM,data:apug7RjFOg==,iv:G0rGljsF0Md/86E9uyF9DAKkSivADtAbqM0Fazh+wWc=,tag:TRlz45b/oaOMOSzA9LPQTA==,type:str]
    admin-password: ENC[AES256_GCM,data:t1+4SQhop2V0G3B+rfJu0OvIFSIDPZfsXCk=,iv:mCHPhGXs3uxZ0bIghMNNA3vMm/RZ1/oR/UvxVaZRbBU=,tag:5vI0qy5XyuimF7i19HEdSA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age14zezx8350dxxh9kpqhpcna7a3gsma24n63qppqy0vfq47vvfkatqry5e9q
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxdHp0NmduK2txeVJ2U05q
            bTJNV2tsQWpCUG1GWERUemJTSDNOS3dDVFhJCnpNeWdjbDZkV2dUZVdrYWNkSlR2
            UlVFdmNUR2ZEdGRUekNpRlF3VUxLY2cKLS0tIFZKU2FGWjBGOVB2TThHb2FrVTAv
            ODlKMkxBdmtZTjZpYkgyd1ZnVllBOGMKXsTVj8IKjn12K2P5rFi9mNLeeKjHyvmW
            g7xcgQX19zPM7ha39eoKKZZORm4+4yDNfzFp9v4LI7yEGSFDyIPZTA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-08-06T20:15:00Z"
    mac: ENC[AES256_GCM,data:J1GFBR/zH54BEUhOBoWJfJSSJUszUfxU/kK3TLdXAEgqYftMGoeKtyVw84/YSlTxuoNyowQbOb4cWW0t9z1PLDHyrUCs1bAzzdIvLbaBou9c4RvaU2lVhq4uAl2e+jz/Xm3mX/TjtglLacCSINepfRP6ypT3PdIyAjkfZenBF5Y=,iv:31Hb4/U0CSkTQC1YqBdbzgLB3TnUuG8l+dD8WCS+loc=,tag:0SR+r8m3fR/2Zs7x0u92sg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
