# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: grafana-admin-creds
    namespace: monitoring
stringData:
    admin-user: ENC[AES256_GCM,data:apug7RjFOg==,iv:G0rGljsF0Md/86E9uyF9DAKkSivADtAbqM0Fazh+wWc=,tag:TRlz45b/oaOMOSzA9LPQTA==,type:str]
    admin-password: ENC[AES256_GCM,data:t1+4SQhop2V0G3B+rfJu0OvIFSIDPZfsXCk=,iv:mCHPhGXs3uxZ0bIghMNNA3vMm/RZ1/oR/UvxVaZRbBU=,tag:5vI0qy5XyuimF7i19HEdSA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age14zezx8350dxxh9kpqhpcna7a3gsma24n63qppqy0vfq47vvfkatqry5e9q
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxdHp0NmduK2txeVJ2U05q
            bTJNV2tsQWpCUG1GWERUemJTSDNOS3dDVFhJCnpNeWdjbDZkV2dUZVdrYWNkSlR2
            UlVFdmNUR2ZEdGRUekNpRlF3VUxLY2cKLS0tIFZKU2FGWjBGOVB2TThHb2FrVTAv
            ODlKMkxBdmtZTjZpYkgyd1ZnVllBOGMKXsTVj8IKjn12K2P5rFi9mNLeeKjHyvmW
            g7xcgQX19zPM7ha39eoKKZZORm4+4yDNfzFp9v4LI7yEGSFDyIPZTA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-03-18T12:26:03Z"
    mac: ENC[AES256_GCM,data:ThEhyMtP0Fa/tqeEWUyIjdXf7XJNVearA8qL1drJgsk/BxjmF80k5kFWQH5qby92cnISl/14CXk4/E0ZHQM+KyFPHcqipw7JvAWPCMWSL7/BMsMGpwcxiR9CdHzSITer5mM9Ipx248P/GrgCgIPk+W0hZdyU9HBnuKGmwUN3rvw=,iv:Jcv1w9BhNF1m5nAfCtreihLVk55SEtdNNNqjL7rAn7o=,tag:R0sjA3JRqsOM6N0eveNQcw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
