# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: grafana-secret
    namespace: monitoring
stringData:
    admin-user: ENC[AES256_GCM,data:apug7RjFOg==,iv:G0rGljsF0Md/86E9uyF9DAKkSivADtAbqM0Fazh+wWc=,tag:TRlz45b/oaOMOSzA9LPQTA==,type:str]
    admin-password: ENC[AES256_GCM,data:t1+4SQhop2V0G3B+rfJu0OvIFSIDPZfsXCk=,iv:mCHPhGXs3uxZ0bIghMNNA3vMm/RZ1/oR/UvxVaZRbBU=,tag:5vI0qy5XyuimF7i19HEdSA==,type:str]
    GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET: ENC[AES256_GCM,data:0hNzZhar17zEY02+cEYuReBP1PkQygVtWQBSo5cU,iv:IVZGaLwHFsk2fXwWpTNP3eF9MHY+fD4/Q1QX+MUmGJ8=,tag:B5Ck4EkzNwvwsWo8UA/sUQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age14zezx8350dxxh9kpqhpcna7a3gsma24n63qppqy0vfq47vvfkatqry5e9q
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxdHp0NmduK2txeVJ2U05q
            bTJNV2tsQWpCUG1GWERUemJTSDNOS3dDVFhJCnpNeWdjbDZkV2dUZVdrYWNkSlR2
            UlVFdmNUR2ZEdGRUekNpRlF3VUxLY2cKLS0tIFZKU2FGWjBGOVB2TThHb2FrVTAv
            ODlKMkxBdmtZTjZpYkgyd1ZnVllBOGMKXsTVj8IKjn12K2P5rFi9mNLeeKjHyvmW
            g7xcgQX19zPM7ha39eoKKZZORm4+4yDNfzFp9v4LI7yEGSFDyIPZTA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-08-06T12:25:45Z"
    mac: ENC[AES256_GCM,data:YafETKDsUJPb0OFzp9Pd/ckwW5ge8yToOp6t6CTawEkvh/WfMCFR/Eg+oa777CAvJ4cOZSdawZI8a/BJ2Kry+1wD52Vuz1n4QazYoyw7MmYNqXWhKV37giaArr7zVvpiaW1Y+hk295dqyRCA3SsZ3IZwSM34oOXwdtkCb83cnxg=,iv:SlqPjn4ioIWYmukxnGBGLtFMIrIAGzTyE3IX6vtUBg4=,tag:/+yu5dVYHVJBj1DHGBQxVA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
