---
# Playbook to handle dns cloud-init problem under fedora > 36 and proxmox
- hosts:
    - master
    - worker
  become: true
  gather_facts: true
  any_errors_fatal: true
  pre_tasks:
    - name: Pausing for 5 seconds...
      ansible.builtin.pause:
        seconds: 5
  tasks:
    - name: Configuration | Install Longhorn packages
      ansible.builtin.dnf: 
        name: 
          - bash
          - curl
          - findmnt
          - grep
          - awk
          - blkid
        state: present

