---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: jellyfin
  namespace: media
spec:
  interval: 5m
  chart:
    spec:
      chart: app-template
      version: 2.6.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s-charts
        namespace: flux-system
  values:
    controllers:
      main:
        type: statefulset
        annotations:
          reloader.stakater.com/auto: "true"

        statefulset:
          volumeClaimTemplates:
            - name: config
              accessMode: ReadWriteOnce
              size: 30Gi
              storageClass: ceph-block
              globalMounts:
                - path: /config

        pod:
          enableServiceLinks: false
          nodeSelector:
            intel.feature.node.kubernetes.io/gpu: "true"
          securityContext:
            supplementalGroups:
              - 44
              - 109
              - 65539

        containers:
          main:
            image:
              repository: jellyfin/jellyfin
              tag: 10.8.13
            env:
              TZ: ${TIMEZONE}
              JELLYFIN_CACHE_DIR: "/config/cache"
              DOTNET_SYSTEM_IO_DISABLEFILELOCKING: "true"
              JELLYFIN_FFmpeg__probesize: 50000000
              JELLYFIN_FFmpeg__analyzeduration: 500000000
            resources:
              requests:
                cpu: 100m
                gpu.intel.com/i915: 1
                memory: 9248M
              limits:
                gpu.intel.com/i915: 1
                memory: 9248M

    service:
      main:
        ports:
          http:
            port: 8096

    ingress:
      main:
        enabled: true
        className: internal-nginx
        hosts:
          - host: &host "jelly.${DOMAIN}"
            paths:
              - path: /
                service:
                  name: main
                  port: http
        tls:
          - hosts:
              - *host
    persistence:
      nfs-nas-media:
        type: nfs
        server: 192.168.178.35
        path: /volume1/media/Video
        globalMounts:
          - path: /media
      transcode:
        type: emptyDir
        globalMounts:
          - path: /transcode
