---
apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: jellyfin-ck
  namespace: media
spec:
  sourcePVC: config-jellyfin-0
  trigger:
    schedule: "0 22 * * *"
  restic:
    copyMethod: Snapshot
    pruneIntervalDays: 14
    volumeSnapshotClassName: csi-ceph-blockpool
    storageClassName: ceph-block
    cacheStorageClassName: local-hostpath
    cacheCapacity: 30Gi
    repository: jellyfin-restic-ck
    retain:
      daily: 14
---
apiVersion: v1
kind: Secret
metadata:
  name: jellyfin-restic-ck
  namespace: media
type: Opaque
stringData:
  # The repository url
  RESTIC_REPOSITORY: s3:https://${S3_EXTERNAL}/jellyfin
  # The repository encryption key
  RESTIC_PASSWORD: "${RESTIC_PW}"
  # ENV vars specific to the back end
  # https://restic.readthedocs.io/en/stable/030_preparing_a_new_repo.html
  AWS_ACCESS_KEY_ID: "${CK_ACCESS_KEY}"
  AWS_SECRET_ACCESS_KEY: "${CK_SECRET_KEY}"
