apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: authelia-data
  namespace: identiy
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: ceph-block
