---
apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: authelia-backup
  namespace: identity
spec:
  sourcePVC: authelia-data
  trigger:
    schedule: "0 22 * * *"
  restic:
    copyMethod: Snapshot
    pruneIntervalDays: 14
    volumeSnapshotClassName: csi-ceph-blockpool
    storageClassName: ceph-block
    cacheStorageClassName: local-hostpath
    cacheCapacity: 1Gi
    repository: authelia-restic-secret
    retain:
      daily: 14
---
apiVersion: v1
kind: Secret
metadata:
  name: authelia-restic-secret
  namespace: identity
type: Opaque
stringData:
  # The repository url
  RESTIC_REPOSITORY: s3:http://192.168.178.35:9000/authelia
  # The repository encryption key
  RESTIC_PASSWORD: "${RESTIC_PW}"
  # ENV vars specific to the back end
  # https://restic.readthedocs.io/en/stable/030_preparing_a_new_repo.html
  AWS_ACCESS_KEY_ID: "${MINIO_USER}"
  AWS_SECRET_ACCESS_KEY: "${MINIO_PASSWORD}"
