---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: external-dns
  namespace: networking
spec:
  interval: 15m
  chart:
    spec:
      chart: external-dns
      version: 1.12.0
      sourceRef:
        kind: HelmRepository
        name: external-dns-charts
        namespace: flux-system
      interval: 15m
  install:
    createNamespace: true
  values:
    image:
        tag: v0.13.2 # TODO: once there's update to this chart, remove tag
    interval: 15m
    logLevel: debug
    provider: pihole
    env:
      - name: EXTERNAL_DNS_PIHOLE_SERVER
        valueFrom:
          secretKeyRef:
            name: pihole-secret
            key: EXTERNAL_DNS_PIHOLE_SERVER
      - name: EXTERNAL_DNS_PIHOLE_PASSWORD
        valueFrom:
          secretKeyRef:
            name: pihole-secret
            key: EXTERNAL_DNS_PIHOLE_PASSWORD

    serviceMonitor:
      enabled: true