apiVersion: v1
kind: Secret
metadata:
    name: pihole-secret
type: Opaque
stringData:
    EXTERNAL_DNS_PIHOLE_SERVER: ENC[AES256_GCM,data:2V3S6GmqBTbexMgRaZsRhz1eol8k3FMM,iv:a54d1Kj3qIUxvJtnAcqQLWwd8BgnbCGfZ0UPvGGNQr8=,tag:UmQUvg6s44kfbEA1Qwud3w==,type:str]
    EXTERNAL_DNS_PIHOLE_PASSWORD: ENC[AES256_GCM,data:nKAJt8A4zBk=,iv:5r7sjpA1PJ08pRBPjf9Vv7yChqZg4k8N2/R5CWLn/0o=,tag:fgNXgP8gB59KhHtBzq5oVA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2023-01-22T16:01:35Z"
    mac: ENC[AES256_GCM,data:J1tlXy9pOnCgoHVj2R7Mqtc/NEbnROOno0Z3QlXPoxQevYSGBBs1p7WulIkGkWk1cW58YM/HbstPhbXQOhX4//vFQG3sNJkXzrbw9gwuhU0xSjIBIM/vh+bwiInW1uq/1imaTqvrO9SffFmlNFDpO+HrUEwjuW3M9iZ63oJAmIg=,iv:K0bDRK72u0JcP8RBOrWw6iiD3usojirF/Tnc3cb0fSs=,tag:9ZiUy0eAb/lTyYQh3pGJRg==,type:str]
    pgp:
        - created_at: "2023-01-22T16:01:35Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA9MZu0oHqP6dARAA0YB/u3RWrhnlnAsZNYiBuo2VaPA4LfNDv7PGJ0v6Y7yn
            i/HJIDaByZgRFOhlwpkO+Me7sbHyvEugYo+RusHpvZuyflYlPNlDjPm4YE0SQWP8
            Uld0SxSOhsgmeCl+GjB1Ow4kMIOyJRdX1uxTP2cb20zNXojZwvo0KvBTPrDwSg7N
            4CpD0ViL8sgeEW8HLldBU23QpiJ7m2Z1jfyjv27sT6oHwsQd7FHGHDNEsYHZT3dv
            xBuA0GlxvUr7UpELikm7FBbDoBWNpUJrrNZ0F1DnOQ5tYfon9CzNhY2gh9aeBDdX
            f69yDE80XsMd650WBO1hoGyFPR03SV3USa/N7/75qgWmNNFIDU4UDr4uNUnNas62
            /w2rw+vurq0unojlVthxx1Q1FgTRCHXLivrcL6odBm8h78BxsqIcReyZ8TD0epMi
            MZWFzIOHtKiLMfhW+WaAqMJydAh3czch5hR+84SmnBnxZXDpuK2vZiKxM/u705n+
            ualYjYgc12fSrWNOeWyiX9NyjS14uI6GjRJWUDxbK5gfouH52jpyW9DcBON1l50u
            /E5De533IAO7HXKUHkE5iYIiknuYy423cg+9Iu+BOTflURcJDmYYMU0woSPBXSP8
            6i9zPbiIplktaDi67X6TjI7nN2d7FuWoddqsT+1Rld990xdtcJKEyzX29IEu/iPS
            XgE6ut3oJN3vaCIsSXd4fu5ROR5U7k3MA8tbP3HFssETCVwgit2Dz7rfcIrTB0nW
            YR4l1Kqj0Ig06v83FsrmeDrvC8yK3lQOwPWBQ19O/9gHIccAdNwngilZjoFFzbU=
            =HUGB
            -----END PGP MESSAGE-----
          fp: EC621778D7E4AD9330404D6A6A00CDA35DF9B2BC
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
