apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:D2wkZs79loD83+Jx,iv:XjaLbXDMR3x8FqtdeRxgpRGm6JGdGqq/1n/ow7WZka4=,tag:xktlUr6Q3DBjYSs9wfk6/w==,type:str]
    SECRET_PRIVATE_DOMAIN: ENC[AES256_GCM,data:sNPW0We6xA79V0g2wYHSIMd3S2MjQhCF,iv:mILwjUVWLQ8Uf+29+4o7Pf9QvZzUS7TU3DyKgxYAEh0=,tag:QKBwM2O5QuAGvmR52Gmm/A==,type:str]
    SECRET_FAM_DOMAIN: ENC[AES256_GCM,data:LsbJDRwlnST0NNbQ1FdtWbc=,iv:o5FgREHjmxH3vrbnMbibOdWXsD34vCRMhBSyH6RhH0Y=,tag:HM7TXOepBpH2350XO5EsHg==,type:str]
    SECRET_PUBLIC_DOMAIN: ENC[AES256_GCM,data:ltdtEk7uXY8=,iv:c2NBtncXLW/T9TkfEQkofcrcjVTenezpG0RQYtFv2t0=,tag:UsqRuEEL2LBxbV1u3VgYNA==,type:str]
    SECRET_EMAIL: ENC[AES256_GCM,data:/vX58Qdf2Poz5hWr6sTr3aMdytYDjHk3smTU,iv:n+f2LMjBWg0moTJqec61aUMwoQBnh0HpFHgOJd9Fe08=,tag:W4XDJ6kqAkKpVAb0g1xOZQ==,type:str]
    CLOUDFLARE_API_TOKEN: ENC[AES256_GCM,data:OU7Arl2JgvgU8n1p4cd8E54zYQun7LVBFyO7dnDgczlaPPYYRxIh1Q==,iv:apufMiDVkPtnhdKKXpUl+J1DYzF2PTOOtsUqCAXv6E4=,tag:vvLB6OR+wjfDs8Eb0+EBrA==,type:str]
    PROM_LOGIN_PW: ENC[AES256_GCM,data:THj6x7uFsN4y8c6alQIjK4NIEQUzMnjuNRQ=,iv:Jl/xnuthKu2YBG7eGVijYQsq/1mwxdxPnpfILYK8cU8=,tag:2D0sUKCTIde4n1jYB06NAw==,type:str]
    SECRET_MQTT_USERNAME: ENC[AES256_GCM,data:WUWWpTt3lhq6,iv:Kt0wkM/tgF18VfhrFwxhgqipc10w3/Y9H/fLMUze9J4=,tag:QhRPlgXWpAL6HgyFLi5dZA==,type:str]
    SECRET_MQTT_PASSWORD: ENC[AES256_GCM,data:6xLc2d/+KMiq8RqyDP0lc7uQaxtT/8c=,iv:jnxOMOEbjE1qdrDyIk3JJUDkEoAAMKIlk8SVWR5Y6xw=,tag:2o9EoYkEgvktvtJrQ33hlw==,type:str]
    SECRET_DNS: ENC[AES256_GCM,data:iL77kpIdPIkSZngj7g==,iv:aWXauAGhm8xh88+xlSm11vJDlMCO24SQnnWrjDz9Zr8=,tag:mad5mmFU9S+vupBvZg3rWg==,type:str]
    SECRET_DNS_KEY: ENC[AES256_GCM,data:Y3Dogypr3qMf2C3GkeH6,iv:vE49Vff6saV1NQwHXKnVCsFDJmJb4vFJ+ckm5WmIUyQ=,tag:Km0ssfYChhJu576ADzZnKw==,type:str]
    SECRET_DNS_SECRET: ENC[AES256_GCM,data:Ss0qx+WwqgKg5Ojk3agY9iGQXt6tw3wvjz048LjYywnPZfPlxj4vgsg0IFs=,iv:7jxFfgs3aJjWOWnIMvsmPbFCODiqLrVaISdBXD5tvK8=,tag:Obb86gyy+9ZML9rub79+rg==,type:str]
    MINIO_USER: ENC[AES256_GCM,data:O58df28mRQU=,iv:YvG2wft1yRuSxrr349p/tNYIi0Cwq/3esfO7sMHlbcE=,tag:9yYrvTEVYvpoFk1Hx7o3RA==,type:str]
    MINIO_PASSWORD: ENC[AES256_GCM,data:KxI2ReXv61W+uSs4zgDVvGZfShKHzJsCw7Y=,iv:tkHc8udyZfvcp0mw0870rVKDIe2YAEY2ZcYyKMZsG80=,tag:VI4d18H+ovAi6vkRhYFWmw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-12-06T20:49:41Z"
    mac: ENC[AES256_GCM,data:VhwW7PczmCJeZnPiMf1KDFtDxX5x25XhyOU4rsoWI/2yqtspJKHi1ieIgYOhiwI0JFEJRL3LNtRFeVQLEicqz23BYjZMFm39f25PGfQycXqMXrCia2/s88z8gGZrIsFQ0cZ+ja7Y2c8oxGpj+jYYkkEYB7BhRNc6udKH094jzAQ=,iv:9DwZJabQ8yoMlbsYKKeF82jBP6nNh/E6PaY8SNIbASM=,tag:3egDFIm6ywCa6hh3zSlh1Q==,type:str]
    pgp:
        - created_at: "2022-08-21T18:09:45Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA9MZu0oHqP6dARAAsaDFO88feVKGSM2Z9jzI3eGUETCQQIheTQCUfN+z9cGo
            3cKcJ8rplXhpOm25bZXqu229wNi2lqsXYMgYKiB03Afkq5Qf+a91K+NYPU6fG0hH
            0nhwk0QEg1MFO020XhVnoG02eAs1q8fb0ta/hPsht6Ckz0IrfcwjQ5eycRybeUbI
            2jM5gNP670AjKkNC6Po0Nb3XgVajA6miH9GXl6Vyz20Z1CwMvRt5FuPsnwm1DNoy
            DUX7evJ1ZNyepBry/9gtC+x7tRKWxtcmiDjyGm8sq2KpO004ZEa20S4gR6/OoCSM
            /WnRQubBFysPc0deoIHqaJ0SeBONOf41E/0M2T4bfx4KdNMSFEFHySyusO4m0EbW
            YMj0i7e21mFFXm9xj36wBh+BS8qEmdBZkQxssuRjB24lOoXNu+wXssuzqdYRCv4k
            BZmvK6OSQZ4T3t1dVQ6rp6JXpaEC0awfbg+QgI7XMGTZntpulH9u+pW0PG2CQCaB
            BTJhoLJKJn9S8Nl88lcFSQh/Dvl9c/Cq2pRwMGyZUi3L/V88PofoyfBdk9d0BCMQ
            8ceGiOoR9m2HfmRkDN+OKn3aynPfjzHymG3q5tm+wkIg8irA6G9NRPfH+9yDN6im
            q5woiG4be9lnlx/+B/+WPyqY6cWJYUQmt24ZxZweT3HpyMiepYmDhvzyojcL/vjS
            XgGlwdq0cR/JppsdQkHkn0pIqRHVGgt2M1HxTcx2SBCCs1CJ91Mprn0uAzhbG2mZ
            wQTYZP/+WSJGdG9pEwyu12yNKdnTLMB6ZOn77PMZdP17pmyoy2TriY8Ek2YgntQ=
            =eqSz
            -----END PGP MESSAGE-----
          fp: EC621778D7E4AD9330404D6A6A00CDA35DF9B2BC
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
