---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: snapshot-controller
  namespace: system
spec:
  interval: 10m
  chart:
    spec:
      chart: snapshot-controller
      version: 2.2.0
      sourceRef:
        kind: HelmRepository
        name: piraeus
        namespace: flux-system
  maxHistory: 3
  install:
    remediation:
      retries: 3
    crds: CreateReplace
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
    crds: CreateReplace
  uninstall:
    keepHistory: false
  values:
    controller:
      serviceMonitor:
        create: true
    webhook:
      enabled: false
