---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-cloudnative-pg
  namespace: flux-system
spec:
  path: ./kubernetes/apps/databases/cloudnative-pg/operator
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-ops-kubernetes
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2beta1
      kind: HelmRelease
      name: cloudnative-pg
      namespace: databases
  interval: 15m
  retryInterval: 1m
  timeout: 30s
