apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-uptime-kuma
  labels:
    usage: uptime-kuma
  namespace: monitoring
spec:
  capacity:
    storage: 4Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    path: /volume3/kubernetes/uptime-kuma
    server: "${NFS_SERVER}"