---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: uptime-kuma-v1
  namespace: home
  labels:
    app.kubernetes.io/name: &name uptime-kuma
    app.kubernetes.io/instance: *name
    snapshot.home.arpa/enabled: "true"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: longhorn