---
apiVersion: volsync.backube/v1alpha1
kind: ReplicationDestination
metadata:
  name: zigbee2mqtt-config-v1
  namespace: home-automation
spec:
  trigger:
    manual: restore-once
  restic:
    destinationPVC: zigbee2mqtt-config-v1
    repository: zigbee2mqtt-restic
    copyMethod: Direct