---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-paperless
  namespace: flux-system
spec:
  path: ./kubernetes/apps/default/paperless/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-ops-kubernetes
  wait: true
  interval: 10m
  dependsOn:
    - name: cluster-apps-paperless-redis
    - name: cluster-apps-volsync
    - name: cluster-apps-rook-ceph-cluster
---
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-paperless-db
  namespace: flux-system
spec:
  path: ./kubernetes/apps/default/paperless/db
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-ops-kubernetes
  wait: true
  interval: 10m
  dependsOn:
    - name: cluster-apps-paperless-redis
    - name: cluster-apps-volsync
    - name: cluster-apps-rook-ceph-cluster
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-paperless-redis
  namespace: flux-system
spec:
  path: ./kubernetes/apps/default/paperless/redis
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-ops-kubernetes
  wait: false
  interval: 10m
