---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: alb-home
  namespace: networking
spec:
  secretName: alb-home-tls
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: "${DOMAIN}"
  privateKey:
    algorithm: RSA
    size: 4096
    rotationPolicy: Always
  dnsNames:
    - "${DOMAIN}"
    - "*.${DOMAIN}"
