---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-authelia
  namespace: flux-system
spec:
  interval: 10m
  path: "./kubernetes/apps/identity/authelia/app"
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-ops-kubernetes
  wait: false
  dependsOn:
    - name: cluster-apps-lldap
