---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-authelia
  namespace: flux-system
spec:
  dependsOn:
    - name: cluster-apps-volsync
    - name: cluster-apps-rook-ceph-cluster
  path: ./kubernetes/apps/identity/authelia/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-ops-kubernetes
  wait: false # no flux ks dependents
  interval: 30m
  retryInterval: 1m
  timeout: 5m
