---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-netcup-ddns
  namespace: flux-system
spec:
  path: ./kubernetes/apps/networking/netcup-ddns/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-ops-kubernetes
  wait: true
  interval: 1m
  retryInterval: 1m
  timeout: 3m
