---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: lldap
  namespace: identity
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 1.5.1
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s-charts
        namespace: flux-system

  values:
    controller:
      replicas: 1
      strategy: Recreate
      annotations:
        reloader.stakater.com/auto: "true"

    image:
      repository: ghcr.io/lldap/lldap
      # TODO: Switch to release tag on next release
      tag: latest-alpine@sha256:a3b65be40ad4e0b8ab9073713bde6c88ae09c811ddc3ab8fcc09e95503f17da1

    env:
      LLDAP_HTTP_PORT: &port 80
      LLDAP_HTTP_URL: https://lldap.${DOMAIN}
      LLDAP_LDAP_PORT: &ldapPort 389
      LLDAP_LDAP_BASE_DN: dc=home,dc=alb

    envFrom:
      - secretRef:
          name: lldap-secret

    service:
      main:
        ports:
          http:
            port: *port
          ldap:
            enabled: true
            port: *ldapPort

    ingress:
      main:
        enabled: true
        ingressClassName: internal-nginx
        hosts:
          - host: &host "lldap.${DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - *host

    persistence:
      data:
        enabled: true
        type: pvc
        existingClaim: lldap-data
    resources:
      requests:
        cpu: 5m
        memory: 128Mi
      limits:
        memory: 512Mi
