apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: identity
resources:
  - ./secret.sops.yaml
  - ./helmrelease.yaml
  - ./pvc.yaml
  #- ./volsync.yaml
  - ./volsync_external.yaml
commonLabels:
  app.kubernetes.io/name: lldap
  app.kubernetes.io/instance: lldap
generatorOptions:
  disableNameSuffixHash: true
  annotations:
    kustomize.toolkit.fluxcd.io/substitute: enabled
