---
apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: lldap-backup-ck
  namespace: identity
spec:
  sourcePVC: lldap-data
  trigger:
    schedule: "0 22 * * *"
  restic:
    copyMethod: Snapshot
    pruneIntervalDays: 14
    storageClassName: ceph-block
    repository: lldap-restic-secret-ck
    moverSecurityContext:
      runAsUser: 1000
      runAsGroup: 1000
      fsGroup: 1000
    retain:
      daily: 14
---
apiVersion: v1
kind: Secret
metadata:
  name: lldap-restic-secret-ck
  namespace: identity
type: Opaque
stringData:
  # The repository url
  RESTIC_REPOSITORY: s3:https://${S3_EXTERNAL}/lldap
  # The repository encryption key
  RESTIC_PASSWORD: "${RESTIC_PW}"
  # ENV vars specific to the back end
  # https://restic.readthedocs.io/en/stable/030_preparing_a_new_repo.html
  AWS_ACCESS_KEY_ID: "${CK_ACCESS_KEY}"
  AWS_SECRET_ACCESS_KEY: "${CK_SECRET_KEY}"
