---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: external-dns
  namespace: networking
spec:
  interval: 15m
  chart:
    spec:
      chart: external-dns
      version: 1.14.1
      sourceRef:
        kind: HelmRepository
        name: external-dns-charts
        namespace: flux-system
      interval: 15m
  install:
    createNamespace: true
  values:
    interval: 3m
    logLevel: debug
    provider: rfc2136
    policy: upsert-only
    sources:
      - ingress
    txtPrefix: "kubernetes."
    txtOwnerId: "default"
    resources:
      requests:
        memory: 100Mi
        cpu: 25m
      limits:
        memory: 250Mi
    extraArgs:
      - --rfc2136-host=${SECRET_DNS}
      - --rfc2136-port=53
      - --rfc2136-zone=${DOMAIN}
      - --rfc2136-tsig-secret=${SECRET_DNS_SECRET}
      - --rfc2136-tsig-secret-alg=hmac-sha256
      - --rfc2136-tsig-keyname=${SECRET_DNS_KEY}
      - --rfc2136-tsig-axfr
      - --source=ingress
      - --domain-filter=${DOMAIN}
    serviceMonitor:
      enabled: true
