---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app uptime-kuma
  namespace: monitoring
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 1.3.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s-charts
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
      remediateLastFailure: true
  values:
    global:
      nameOverride: *app
    image:
      repository: louislam/uptime-kuma
      tag: 1.19.6
    service:
      main:
        ports:
          http:
            port: 3001
    persistence:
      config:
        enabled: true
        existingClaim: uptime-kuma-pvc-2
        mountPath: /app/data
    ingress:
      main:
        enabled: true
        ingressClassName: nginx
        annotations:
          cert-manager.io/cluster-issuer: letsencrypt-production
        hosts:
          - host: &host "uptime.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - *host
            secretName: uptime-tls
    resources:
      requests:
        cpu: 10m
        memory: 50Mi
      limits:
        memory: 150Mi