apiVersion: v1
kind: Secret
metadata:
    name: cnpg-backup
    namespace: databases
    label:
        cnpg.io/reload: "true"
stringData:
    ACCESS_KEY_ID: ENC[AES256_GCM,data:qw3AiFriQQ2v8Bvkm+relQ==,iv:mGaLJ46r6jJUGpngjRcIW+7K9wgmkR4UTPmnysNVYts=,tag:IiVdG0abWkveZ7lJYhmkHQ==,type:str]
    ACCESS_SECRET_KEY: ENC[AES256_GCM,data:7FZHnWfTMYr/1sLIseA/i5lnlmli9YodRA9PhH/jBqc=,iv:Z2ZWv5IaauaAJ4ozmonm/mDdKQc2qcAqJVisKOLaHFc=,tag:ykU7+WQIodIivDVGbvzcSg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age14zezx8350dxxh9kpqhpcna7a3gsma24n63qppqy0vfq47vvfkatqry5e9q
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFcU9QNHE0UkdLYXQxTE1H
            cDQ4TEZjVWU2YTlCcWVXRm1vcm9UL1g2WEJzCjFnSFVDcGJ1MENTekZXNkJlamlT
            NWtIajJ6TlZpRjVzQU1PZ3Y1UEVmQUUKLS0tIGhYbm53a2N2amNHV3JDU2ZPbVYy
            NHl4T1R5REhmMS9KeWpvRmJXMTRzem8KkL72UITJ9kKABalGjTplE65HhJEIRgg6
            lj3gZ+4ihmzDVptQ6srfy/xGB24tozKM1ZSWFYwFx4J3F0YbxlJpUQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-05-18T18:33:23Z"
    mac: ENC[AES256_GCM,data:TB4ywQVuCNE4pLdGdloKlnNTwn5sZbqrOOVoy58A0xAY5NWKW4vVJJPE1WBTyqAArLUm6moti5OXrzCnsiHzj0w+Ix9Hs1zdS+tb+mdIB4ewwtXiV6wLRqRmGVeucGz1VHWOH/y8MJK+Yy168Mmi2NsRsBONnXQqpBk1w9x4XGA=,iv:FoBLDTGvb/oVNop5os9osrUsJwsKoeRrS0Bvm8rV0gA=,tag:+5VtBqg3tZvTi3hITuJQvw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
---
apiVersion: v1
kind: Secret
#type: kubernetes.io/basic-auth
metadata:
    name: cloudnative-pg
    namespace: databases
stringData:
    username: ENC[AES256_GCM,data:4TJ0pSuEdw==,iv:8sQbkRW8KeATD8CJLsrF3qSiFNK+AE9n5L1rP6foegM=,tag:u/Dgzts57nlgkrfZXE1gOQ==,type:str]
    password: ENC[AES256_GCM,data:oblgsP2tIRlPO0ATWbuX3i2nPhZ5Nz2fs41fXdii5Sp7,iv:Mv5bC05SAgAKBqQ1f5S9AZAE9uycqdizwLnPkBIKk1Y=,tag:yuiHJnuLMkYxJjrOuX9ODg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age14zezx8350dxxh9kpqhpcna7a3gsma24n63qppqy0vfq47vvfkatqry5e9q
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFcU9QNHE0UkdLYXQxTE1H
            cDQ4TEZjVWU2YTlCcWVXRm1vcm9UL1g2WEJzCjFnSFVDcGJ1MENTekZXNkJlamlT
            NWtIajJ6TlZpRjVzQU1PZ3Y1UEVmQUUKLS0tIGhYbm53a2N2amNHV3JDU2ZPbVYy
            NHl4T1R5REhmMS9KeWpvRmJXMTRzem8KkL72UITJ9kKABalGjTplE65HhJEIRgg6
            lj3gZ+4ihmzDVptQ6srfy/xGB24tozKM1ZSWFYwFx4J3F0YbxlJpUQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-05-18T18:33:23Z"
    mac: ENC[AES256_GCM,data:TB4ywQVuCNE4pLdGdloKlnNTwn5sZbqrOOVoy58A0xAY5NWKW4vVJJPE1WBTyqAArLUm6moti5OXrzCnsiHzj0w+Ix9Hs1zdS+tb+mdIB4ewwtXiV6wLRqRmGVeucGz1VHWOH/y8MJK+Yy168Mmi2NsRsBONnXQqpBk1w9x4XGA=,iv:FoBLDTGvb/oVNop5os9osrUsJwsKoeRrS0Bvm8rV0gA=,tag:+5VtBqg3tZvTi3hITuJQvw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
