---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app gitea
  namespace: utilities
spec:
  interval: 15m
  chart:
    spec:
      chart: *app
      version: 7.0.4
      sourceRef:
        kind: HelmRepository
        name: *app
        namespace: flux-system
      interval: 15m
  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  values: