apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-paperless-data
  labels:
    usage: paperless-data
  namespace: home
spec:
  capacity:
    storage: 1024Mi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    path: /volume3/kubernetes/paperless/data
    server: "${NFS_SERVER}"
