---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: paperless-ngx-postgresql
  namespace: default
spec:
  interval: 5m
  chart:
    spec:
      chart: postgresql
      version: 12.4.3
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
      interval: 5m
  targetNamespace: default
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    image:
      repository: bitnami/postgresql
      tag: 15.2.0
    auth:
      username: paperless-ngx
      password: ${SECRET_PAPERLESS_NGX_DB_PASSWORD}
      database: paperless-ngx
    primary:
      persistence:
        enabled: true
        existingClaim: paperless-db-data-v1
#    volumePermissions:
#      enabled: true
#      image:
#        repository: bitnami/bitnami-shell
#        tag: 11
#    metrics:
#      enabled: "${MONITORING_PROMETHEUS}"
#      serviceMonitor:
#        enabled: "${MONITORING_PROMETHEUS}"
#      image:
#        repository: bitnami/postgres-exporter
#        tag: 0.11.1