---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: paperless-db-data-v1
  namespace: default
spec:
  storageClassName: ceph-block
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi