---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-nextcloud
  namespace: flux-system
spec:
  path: ./kubernetes/apps/default/nextcloud/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-ops-kubernetes
  wait: true
  interval: 10m
  dependsOn:
    - name: cluster-apps-rook-ceph-cluster
    - name: cluster-apps-nextcloud-database
    - name: cluster-apps-volsync
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-nextcloud-database
  namespace: flux-system
spec:
  path: ./kubernetes/apps/default/nextcloud/database
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-ops-kubernetes
  wait: true
  interval: 10m
  dependsOn:
    - name: cluster-apps-rook-ceph-cluster
