---
# yaml-language-server: $schema=https://kubernetes-schemas.devbu.io/helmrelease_v2beta1.json
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: emqx
  namespace: home-automation
spec:
  interval: 15m
  chart:
    spec:
      chart: emqx
      version: 5.0.19
      sourceRef:
        kind: HelmRepository
        name: emqx
        namespace: flux-system
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    image:
      repository: public.ecr.aws/emqx/emqx
    replicaCount: 3
    recreatePods: true
    emqxConfig:
      EMQX_ALLOW_ANONYMOUS: "false"
      EMQX_AUTH__MNESIA__PASSWORD_HASH: plain
      EMQX_DASHBOARD__DEFAULT_PASSWORD: ${SECRET_MQTT_PASSWORD}
      EMQX_AUTH__USER__1__USERNAME: ${SECRET_MQTT_USER}
      EMQX_AUTH__USER__1__PASSWORD: ${SECRET_MQTT_PASSWORD}
    emqxAclConfig: >
        {allow, {user, "dashboard"}, subscribe, ["$SYS/#"]}. {allow, {ipaddr, "127.0.0.1"}, pubsub, ["$SYS/#", "#"]}. {allow, all, subscribe, ["$SYS/#", {eq, "#"}]}. {allow, all}.
    emqxLoadedPlugins: >
      {emqx_management, true}. {emqx_recon, true}. {emqx_retainer, true}. {emqx_dashboard, true}. {emqx_telemetry, false}. {emqx_rule_engine, true}. {emqx_bridge_mqtt, false}. {emqx_auth_mnesia, true}. {emqx_prometheus, true}.
    emqxLoadedModules: >
      {emqx_mod_presence, true}. {emqx_mod_delayed, false}. {emqx_mod_rewrite, false}. {emqx_mod_subscription, false}. {emqx_mod_topic_metrics, true}.

    service:
      type: LoadBalancer
      loadBalancerIP: '${SVC_MQTT_ADDR}'
      externalTrafficPolicy: Local
    ingress:
      dashboard:
        enabled: true
        ingressClassName: nginx
        path: /
        pathType: Prefix
        hosts:
          - &host "emqx.${SECRET_DOMAIN}"
        tls:
          - hosts:
              - *host
    metrics:
      enabled: false
    persistence:
      enabled: true
      storageClass: longhorn
      size: 100Mi
    affinity:
      podAntiAffinity:
        preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                  - key: app.kubernetes.io/name
                    operator: In
                    values:
                      - emqx
              topologyKey: kubernetes.io/hostname
    resources:
      requests:
        cpu: 100m
        memory: 150Mi
      limits:
        memory: 512Mi
  #valuesFrom:
  #  - targetPath: emqxConfig.EMQX_DASHBOARD__DEFAULT_PASSWORD
  #    kind: Secret
  #    name: emqx-config
  #    valuesKey: admin_password
  #  - targetPath: emqxConfig.EMQX_AUTH__USER__1__USERNAME
  #    kind: Secret
  #    name: emqx-config
  #    valuesKey: user_1_username
  #  - targetPath: emqxConfig.EMQX_AUTH__USER__1__PASSWORD
  #    kind: Secret
  #    name: emqx-config
  #    valuesKey: user_1_password