---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: home-automation
resources:
  - ./secret.sops.yaml
  - ./helm-release.yaml
labels:
  - pairs:
      app.kubernetes.io/name: emqx
      app.kubernetes.io/instance: emqx