# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: vaultwarden
    namespace: home
stringData:
    ADMIN_TOKEN: ENC[AES256_GCM,data:LmKbjpOHwTk5nQN+yAizvRdjK1HP3wp/cfoNt71f/VBdaoeRSfDRADXH79sefb//1UZh1yRMdSGNCjCzMwEqgA==,iv:FV/0w8DlZTVKLLemDF6TikV0/HzayUPUESKWtRUfkyM=,tag:ZL+AXACa+K3EF1P4DhkxRw==,type:str]
    SMTP_FROM: ENC[AES256_GCM,data:5nvsit6i08z5G96IRoJTxQxjboNTvxH14O1RiGA=,iv:3rxPfnVQllHw18+LdNYMabSlee/1PkDPVuxbYuUpEzs=,tag:OV4mVjc2TSFs1flA1lVtHA==,type:str]
    SMTP_USERNAME: ENC[AES256_GCM,data:0w6bj7sZsmh4bA6XR6zrhdN33i/HjCqBfP3UtQ==,iv:ZmTjZc/q1Oqul5Xq9e/NNeCWofgez+43/Z7EL+pEWns=,tag:CzJ3SYpRoEYPf0F93UiV6A==,type:str]
    SMTP_PASSWORD: ENC[AES256_GCM,data:7rZnCbu+tk59wIZHurQ5UCGmrpPU,iv:rZs5Wo106F4GX5U4yFvYTVKs3cWeAlVJewReowsnUJg=,tag:ssF27pc5I20CpQL8ojd2Ng==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2023-01-22T16:00:53Z"
    mac: ENC[AES256_GCM,data:TEemKuNNqCHRqpsLdMPRe9zB0066BhLnk0HYQMdCcqIJlLGx1w8rwoFbriayePBMKF/BuauIHe6gmOoV4rIw6NJkUQwFdGsn+guanRy9lzCsTPEhZaetck8WG19rkPmWaRvo/BLfo1MzY2hFYvrTKLStlQW8MZXm6gp789HcpUY=,iv:bT22eqT4squ+BkUwoLqQNghFesNKAPGDd2VQXz3xi3U=,tag:z41mZqSeYcgAddUR75VhWw==,type:str]
    pgp:
        - created_at: "2023-01-22T16:00:53Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA9MZu0oHqP6dARAA2QEfQQGkUiUz/9D3Nu51jl2IVrA+tBCXTErNkB02CvWI
            pMyAsQ9DGGqFsU82hA7UC+RD/dndtZDwUhSv4yq/cYY2KZZgmpQPnwIv2bbsIPtQ
            sisocDxKlnAVWpumXkcqoV7uMobu/X8/kEFUD85w6939EZGUIniD+MBnmqAXRb/0
            tvDj4xGK68zqpU6kXV0VE+BLeQsMrp3dTHUaY5aZNWv5zNjVMNGs3kaZY3lXkBIl
            HnWk/cnD427eO/rFXeEfH3PIc202nUMBktam/FA8SDXKz/sEGxOp3I6WQSko1OjO
            RzxZxgVx3DrT4irv3EjrTrz4u03y5G0LK2Y/6uqu1bXuFAOkzD3qsSXk4CNFJFj2
            M9DEFHlSI6fIXv0qQlNlOpqdEckL3tbAUDxFffLX/L1JhoTB8kavzfGAAr4tTWk5
            TgnubRoN23oW2r3aTyWn6UIQW3pkgqOPLUT4CGrB/0qmu0RviXvSzPxhzbrzUzMW
            qiFZWpqESYoEiucx7fDIRO7tcMXB4myqmzRIC6rG6H4UErP9YuJbiJAhNo2pzxTf
            1uxgk/EoGZOVckl55xxVer1TOMpMH4Dl0FmPWsFK2oLeDY5RcD6IYdVAL3xNGR+t
            TYPzF8VPwUTkZP3UFi0/IdwHs8jvJzXLQskf/RLo01xr22KbaqgQT9W5xaR3HeLS
            XgF6iMM/sGuhWVoR59AyYa+ia2g8kgLMmfKRrijfaDOB+vccCVuy3G7NcsZUumlD
            htY1VRe9OOjZMhwBiYITO7JfzO8FkB5BjBGN7NWaMnr3B0rbLvUpl6BFqwmpxB4=
            =lbzA
            -----END PGP MESSAGE-----
          fp: EC621778D7E4AD9330404D6A6A00CDA35DF9B2BC
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
