---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/upgrade.cattle.io/plan_v1.json
apiVersion: upgrade.cattle.io/v1
kind: Plan
metadata:
  name: agent
spec:
  # renovate: datasource=github-releases depName=k3s-io/k3s
<<<<<<< HEAD
  version: "v1.29.1+k3s1"
=======
  version: "v1.29.1+k3s2"
>>>>>>> b40ba09588cafecdb6e7c6142780acf53d3783bd
  serviceAccountName: system-upgrade
  concurrency: 1
  nodeSelector:
    matchExpressions:
      - {key: node-role.kubernetes.io/control-plane, operator: DoesNotExist}
  prepare:
    image: rancher/k3s-upgrade
    args: ["prepare", "server"]
  upgrade:
    image: rancher/k3s-upgrade
