---
apiVersion: volsync.backube/v1alpha1
kind: ReplicationDestination
metadata:
  name: jellyfin-restic-restore
  namespace: home
spec:
  trigger:
    manual: restore-once
  restic:
    destinationPVC: jellyfin-config-v1
    repository: jellyfin-restic-config
    copyMethod: Direct