---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: snapshot-controller
  namespace: kube-system
spec:
  interval: 10m
  chart:
    spec:
      chart: snapshot-controller
      version: 1.7.2
      sourceRef:
        kind: HelmRepository
        name: piraeus
        namespace: flux-system
  maxHistory: 3
  install:
    remediation:
      retries: 3
    crds: CreateReplace
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
    crds: CreateReplace
  uninstall:
    keepHistory: false
  values:
    volumeSnapshotClasses:
      - name: longhorn
        driver: driver.longhorn.io
        annotations:
          snapshot.storage.kubernetes.io/is-default-class: "true"
    serviceMonitor:
      create: true