apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:9N0l4vI79kNFcKMK,iv:ZtmFdLcRmVi2K1+/OvqF8H7yV7JcOmnpaF9VrVg6Irg=,tag:HzJH1+axPWJC+jrVDeyIVA==,type:str]
    SECRET_PRIVATE_DOMAIN: ENC[AES256_GCM,data:GWTC9tviL7ME4Pcqd3Y25x/NCwcw8D8m,iv:pXl3Sgl7IrmdHLaF28IeufanFZ8xSFKXmcjHocEMuMk=,tag:mIfJAnq58CFhxe6b2fL1hg==,type:str]
    SECRET_FAM_DOMAIN: ENC[AES256_GCM,data:JXhkUF8P6T6g9mlAuBbEQRM=,iv:isHapu9Snit7YOROsgD+i5VYZvbQD9aztD4qvYD5bo4=,tag:NAT2YmDUINenR5mNV438iw==,type:str]
    SECRET_PUBLIC_DOMAIN: ENC[AES256_GCM,data:ygxXv03T0dg=,iv:vnhxPG/yqrzVH1aCMurCwhvLX3kXQnrILEws/v2D/2Q=,tag:u/3PTyhhYmp35HCHtqOY8g==,type:str]
    SECRET_EMAIL: ENC[AES256_GCM,data:hE/uq0z4XPlmB4zYJCeLhn3ILObAJGj5Jyqa,iv:GCXFbrkKKQz4iYq28jv/Gje/0YwcaVptQBoO/F4B+yo=,tag:mWyGUD5QZ/dJJqYe++FfIw==,type:str]
    CLOUDFLARE_API_TOKEN: ENC[AES256_GCM,data:UpmfH4S5z7kCcP6/63Bc01IDfm9WC+KXDoNiuT3fimJeuuoVQ+vq/Q==,iv:nstz92tr4sxILD/uAcWF+FhyDnhe7dTjnJFpcBfDnYU=,tag:RFWEb+SLYbpCA01mmhcdng==,type:str]
    PROM_LOGIN_PW: ENC[AES256_GCM,data:rv233IA42i522dHgARD3INpU6gayM7lkoa4=,iv:dY2T1jTbyiKB2/VpRWnV5RTsYlT6S8IMLXSObQY9NRM=,tag:qnRLaC7w/WjV78KJn1f2Gg==,type:str]
    SECRET_MQTT_USERNAME: ENC[AES256_GCM,data:M3Zi8xF9Q7v+,iv:AUBxCmIbSmBd0toQKHqJSUxdreJAqZeOnt2T56UIUNM=,tag:/aog8RDVeb6eeu4RlnMc2Q==,type:str]
    SECRET_MQTT_PASSWORD: ENC[AES256_GCM,data:PItlGfEfyQgypsiZPHDKxuAs69OvQNE=,iv:v4HEcqut7ip8LrRcGnOnMTjsZvISoqkIO4SpwUWYG04=,tag:MtnqIJB+zAc5pdKtlP7t1g==,type:str]
    SECRET_DNS: ENC[AES256_GCM,data:SD74n3CT1Et1yFvrXQ==,iv:6sDGsTAPWa44I+Ez/VlM5RM78zMF9dd2Gk65x/13qCQ=,tag:cbB8vdIvqPSyA0bb34/SPA==,type:str]
    SECRET_DNS_KEY: ENC[AES256_GCM,data:786bhVF/HT2b4G8=,iv:AnRK7tqrvdG/DgPIwlPBVEclbd60hFOEPeb+//77FU8=,tag:VDNQ9AvKDga1GLj59tE8pA==,type:str]
    SECRET_DNS_SECRET: ENC[AES256_GCM,data:XdVPzTPiKBfF1SdhXBxRISszgnFgW8+MCLgvR8e4RI5NS4bEGSXrX6/9XBw=,iv:vQvRGAulJi7GTUhVf62CthNQII24WoWkzfal7HX7/GE=,tag:f5Jg1wpmqlqlkoq9mA5dOQ==,type:str]
    MINIO_USER: ENC[AES256_GCM,data:WVqnn5NnJKU=,iv:LctQSBkvTOIWTa39/ES9pXb78XHMp5NmZty2di5k6LY=,tag:ukN4pdKmqMZOAkLRH7uFRQ==,type:str]
    MINIO_PASSWORD: ENC[AES256_GCM,data:R7EP+yil29+T5Hu3GfKr3hj2DTQ6qoxHCXQ=,iv:1nK2lRfmeI9L12uJ3UiiTdh+FyMTR34ednbTVrfM9ck=,tag:TGbWK5tMkNwcBS206ngBtg==,type:str]
    RESTIC_PW: ENC[AES256_GCM,data:xKSc+M4L0Zz5GI4NW2g7T3ps0Pc=,iv:6kyUNQV+jkNLjNV/2H7FB28Qbl6X/aRG9R9uREibouU=,tag:uUWBMEmUKkx8mYw8FNr7cQ==,type:str]
    JELLYFIN_API_KEY: ENC[AES256_GCM,data:AtiKjaRwcGtbDj9dX5i3NcnuVEpHDlnNjOPtxGl6Sdk=,iv:FSWnpr0rMxfATlxQw7RFl9VSMb7PYEDsy0oYgUZVJOI=,tag:BHraGTOVSAW/M5vVaaYu8A==,type:str]
    PIHOLE_PASSWORD: ENC[AES256_GCM,data:tCdpevoLa5c=,iv:mF8ExshG9OB+6FV6XRwHY1wbnvYsql1DTWxNuvMRCGQ=,tag:HWxKpkHqjoVuNg3p0hMZng==,type:str]
    FRITZ_PASSWORD: ENC[AES256_GCM,data:nbZPdzHNi5Jft5xNXv6K7qVb,iv:F1PJpgO7Mru/ZWAGf1DbXGJRD4fLFUwme+oDi/3Uo3A=,tag:2syztrtsHto+dOScGhJ0iA==,type:str]
    FRITZ_IP: ENC[AES256_GCM,data:v9IhmOcmgR6TTH32Og==,iv:cqhy54TBjldNFtub9XN0IG4hY03hAozt/aonYseGM4c=,tag:fpZ5AjcHHCToQhmDZ8SN3g==,type:str]
    FRITZ_USER: ENC[AES256_GCM,data:fj5aal62WrBNDmUSyMo=,iv:Ya3zH7MAHjrZuzkWLkky3LvF8PHrGxHthAnmerdDYQw=,tag:BjAu39D147yT4UH5Fazuuw==,type:str]
    SECRET_PAPERLESS_NGX_SECRET_KEY: ENC[AES256_GCM,data:nFMccUpndoEYDQdWDQPyTARgz+m0qC3WVEWSJPnu9m+iXhQ+GHqezw==,iv:FibjQXANHlZyXVesCXRFQ37E6mUNDy0JDgs73SW4dzY=,tag:+cKopZ447lODBV+44nYLxw==,type:str]
    SECRET_PAPERLESS_NGX_DB_PASSWORD: ENC[AES256_GCM,data:GMSBsRmLcq9bUWlT9wSFjOkywfYBC2hHYrynyx/X,iv:JQvmC8Nl24E2RhbtVyTqBMmjdgf3uaJS5w4s1YngLP8=,tag:FE89//1U2vBGOGtAo0b72w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ce6neraa02llughs9qcw75u0jr9avef64fy2zln7vy8qu98mky2qxm59ju
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVTmhGak1jbDl5UG1INmlW
            eFlHZFB2cnd1MHNydFMrMWRNWVdpTWRQb3pBCmFyeEtmUU55KzVlWlBYbXN3dlhr
            OUlxdjh0enA2ekFMSlNqTmxDSVFMNmcKLS0tIFF1L3Z4S1Y2NzljSXZUM2NPQ1Rw
            T2FWSTU2bUNya3FEcDRsWkdtMGNlRW8KqAnc0SyYk84Vlt/ZYrnWvakKVT/aVF2X
            8VC5Ha4JSs4s1xoWkALri1PZahsY8g6AJFoseCGcmv18qYawt62S8w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-03-02T13:37:38Z"
    mac: ENC[AES256_GCM,data:ZmFojB+kTbhhYl02E178x5GCzKGluS76qdfHi0sXOIXL3l0BWBQsY/99FNeivmK6NZamsgOPNHz6KFrhC7EoTt42595n6Xd97BsiWLU4x0/eWKRgnZuz0PUmzmC8+NQ/nTvtRnlLOgfUr0ds6srh4TbiDSTlXEUj52Tto0GyC2A=,iv:taFSSUCxvWRSo6QapFnvqy5QGtvQPzyNAGqbyabHALo=,tag:4u2fKvYPkiFUe6j6LE04Sg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
