apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./external-dns/ks.yaml
  - ./ingress-nginx/ks.yaml
  - ./cloudflare-ddns/ks.yaml
 # - ./cloudflared/ks.yaml
  - external-services
  - namespace.yaml
