apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ./metallb/ks.yaml
- ./external-dns/ks.yaml
- ./ingress-nginx/ks.yaml
- ./cloudflare-ddns/ks.yaml
#- ./netcup-ddns/ks.yaml
- ./pihole/ks.yaml
- ./k8s-gateway/ks.yaml
- external-services
- namespace.yaml