---
apiVersion: "acid.zalan.do/v1"
kind: postgresql
metadata:
  name: postgres
  namespace: database
spec:
  teamId: "alb-home"

  volume:
    size: 30Gi

  numberOfInstances: 3

  users:
    postgres: # database owner
      - superuser
      - createdb

  postgresql:
    version: "15"