---
storage:
  encryption_key: a_very_important_secret
  local:
    path: /config/db.sqlite3

access_control:
  default_policy: deny
  networks:
    - name: internal
      networks:
        - "10.0.0.0/8"
        - "172.16.0.0/12"
        - "192.168.0.0/16"
  rules:
    - domain:
        - "echo-server.${DOMAIN}"
      policy: one_factor
      subject:
        - ["group:admins"]

    - domain:
        - "bookmarks.${DOMAIN}"
      resources:
        - "^/api/.*$"
      policy: bypass
    - domain:
        - "bookmarks.${DOMAIN}"
      policy: two_factor
      subject:
        - ["group:admins"]
    - domain:
        - "draw.${DOMAIN}"
      policy: one_factor
      subject:
        - ["group:admins"]
    - domain:
        - "prometheus.${DOMAIN}"
      policy: two_factor
      subject:
        - ["group:admins"]
    - domain:
        - "alertmanager.${DOMAIN}"
      policy: two_factor
      subject:
        - ["group:admins"]
    - domain:
        - "freshrss.${DOMAIN}"
      policy: one_factor
      subject:
        - ["group:admins"]
    - domain:
        - "freshrss.${DOMAIN}"
      resources:
        - "^/api/.*$"
      policy: bypass
identity_providers:
  oidc:
    cors:
      endpoints:
        - "authorization"
        - "token"
        - "revocation"
        - "introspection"
      allowed_origins_from_client_redirect_uris: true
    clients:
      - id: grafana
        description: Grafana
        secret: "${GRAFANA_OAUTH_CLIENT_SECRET}"
        public: false
        authorization_policy: two_factor
        pre_configured_consent_duration: 1y
        scopes:
          - "openid"
          - "profile"
          - "groups"
          - "email"
        redirect_uris:
          - "https://grafana.${DOMAIN}/login/generic_oauth"
        userinfo_signing_algorithm: none
