---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: paperless-ngx-postgresql
  namespace: paperless-ngx
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 4Gi