---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: paperless-ngx-data
  namespace: paperless-ngx
spec:
  storageClassName: ceph-block
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 50Gi