---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: home-assistant
  namespace: home-automation
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 2.4.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s-charts
        namespace: flux-system
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    controllers:
      main:
        type: statefulset
        annotations:
          reloader.stakater.com/auto: "true"

        pod:
          hostNetwork: true
          dnsPolicy: ClusterFirstWithHostNet

        statefulset:
          volumeClaimTemplates:
            - name: config
              mountPath: /config
              accessMode: ReadWriteOnce
              size: 20Gi
              storageClass: ceph-block

        containers:
          main:
            image:
              repository: ghcr.io/home-assistant/home-assistant
              tag: 2024.1.3
            env:
              TZ: "Europe/Berlin"
           #   SECRET_RECORDER_DB_URL:
            probes:
              liveness:
                enabled: false
              readiness:
                enabled: false
              startup:
                enabled: false
            resources:
              requests:
                cpu: 10m
                memory: 1250Mi
              limits:
                memory: 2500Mi

 #         codeserver:
 #           image:
 #             repository: ghcr.io/coder/code-server
 #             tag: 4.19.1@sha256:993c381c28a3738b903ac21180f5f9dab8f2aa547bbb0b9d69bea558691e10d3
 #             pullPolicy: IfNotPresent
 #           env:
 #             TZ: "Europe/Berlin"
 #             HASS_SERVER: http://localhost:8123
 #             HASS_TOKEN: ${SECRET_HASS_TOKEN}
 #             PASSWORD: ${SECRET_HASS_PASSWORD}
 #           args:
 #             - --user-data-dir
 #             - "/config/.vscode"
 #             - --auth
 #             - "password"
 #             - --port
 #             - "12321"
 #             - "/config"
 #           volumeMounts:
 #             - name: config
 #               mountPath: /config

    service:
      main:
        type: LoadBalancer
        annotations:
          io.cilium/lb-ipam-ips: 192.168.178.243
        ports:
          http:
            port: 8123
          mdns-tcp:
            enabled: true
            port: 5353
            protocol: TCP
            targetPort: 5353
          mdns-udp:
            enabled: true
            port: 5353
            protocol: UDP
            targetPort: 5353
          homekit:
            port: 21063

    ingress:
      main:
        enabled: true
        ingressClassName: internal-nginx
        hosts:
          - host: &host "hass.${DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
                service:
                  name: main
                  port: http
        tls:
          - hosts:
              - *host
#      codeserver:
#        enabled: true
#        className: internal-nginx
#        hosts:
#          - host: "hass-vscode.${DOMAIN}"
#            paths:
#              - path: /
#                pathType: Prefix
#                service:
#                  name: codeserver
#                  port: http
#        tls:
#          - hosts:
#              - hass-vscode-tls
