---
apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: vaultwarden-restic-backup
  namespace: home
spec:
  sourcePVC: vaultwarden-v5
  trigger:
    schedule: "30 20 * * *"
  restic:
    pruneIntervalDays: 15
    repository: vaultwarden-restic-config
    retain:
      hourly: 1
      daily: 1
      weekly: 1
      monthly: 1
      yearly: 1
    copyMethod: Clone