---
tunnel: ${SECRET_CLOUDFLARE_TUNNEL_ID}
credentials-file: /etc/cloudflared/credentials.json
no-autoupdate: true

ingress:
  - hostname: "*.${DOMAIN}"
    service: https://external-ingress-nginx-controller.networking.svc.cluster.local:443
    originRequest:
      originServerName: "ingress.${DOMAIN}"
  - service: http_status:404
