---
tunnel: ${SECRET_CLOUDFLARE_TUNNEL_ID}
credentials-file: /etc/cloudflared/credentials.json
originRequest:
  connectTimeout: 30s
warp-routing:
  enabled: false

ingress:
  - hostname: "*.${DOMAIN}"
    service: https://ingress-nginx-controller.networking
    originRequest:
      noTLSVerify: true
  - service: http_status:404