---
tunnel: ${SECRET_CLOUDFLARE_TUNNEL_ID}
credentials-file: /etc/cloudflared/credentials.json
originRequest: # Top-level configuration
  connectTimeout: 30s
warp-routing:
  enabled: false

ingress:
  # The localhost:8000 service inherits all root-level configuration.
  # In other words, it will use a connectTimeout of 30 seconds.
  - hostname: grafana.${DOMAIN}
    service: https://ingress-nginx-controller.networking.svc.cluster.local:443
    originRequest:
      httpHostHeader: grafana.${DOMAIN}
  # - hostname: example2.com
  #   service: localhost:8001
  # The localhost:8002 service overrides some root-level config.
  # - service: localhost:8002
  #   originRequest:
  #     connectTimeout: 10s
  #     disableChunkedEncoding: true
  # Some built-in services such as `http_status` do not use any configuration.
  # The service below will simply respond with HTTP 404.
  - service: http_status:404