---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: &app cloudflared
  namespace: networking
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 1.5.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s-charts
        namespace: flux-system
      interval: 15m
  maxHistory: 15
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    controller:
      replicas: 2
      strategy: RollingUpdate
      annotations:
        reloader.stakater.com/auto: "true"
    image:
      repository: cloudflare/cloudflared
      tag: 2023.10.0-amd64
    args: ['tunnel', '--config', '/etc/cloudflared/config.yaml', '--metrics', '0.0.0.0:9090', 'run']
    service:
      main:
        nameOverride: metrics
        ports:
          http:
            port: 9090
    persistence:
      config:
        enabled: true
        type: custom
        volumeSpec:
          configMap:
            name: &config cloudflare-tunnel
        subPath:
          - path: config.yaml
            mountPath: /etc/cloudflared/config.yaml
            readOnly: true
      credentials:
        enabled: true
        type: custom
        volumeSpec:
          secret:
            secretName: &secret cloudflared-credentials
        subPath:
          - path: credentials.json
            mountPath: /etc/cloudflared/credentials.json
            readOnly: true
    resources:
      requests:
        memory: 64Mi
        cpu: 10m
      limits:
        memory: 128Mi
    podAnnotations:
      secret.reloader.stakater.com/reload: *secret
      configmap.reloader.stakater.com/reload: *config
    topologySpreadConstraints:
      - maxSkew: 1
        topologyKey: kubernetes.io/hostname
        whenUnsatisfiable: DoNotSchedule
        labelSelector:
          matchLabels:
            app.kubernetes.io/name: cloudflared