---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - cert-manager
  - databases
  #- home
  #- home-automation
  - monitoring
  - networking
  - kube-system
  - tigera-operator
  - storage
  - volsync
  - rook-ceph
  - default
  - system-upgrade
  - flux-system
  - kyverno
#  - security
