---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - cert-manager
  - database
  - identity
  - monitoring
  - networking
  - security
  - kube-system
  - media
  - home-automation
  - selfhosted
  - volsync
  - rook-ceph
  - default
  - flux-system
  - kyverno
  - system
