---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mealie-config-v1
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
  storageClassName: ceph-block