---
apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: mealie
  namespace: default
spec:
  sourcePVC: mealie-config
  trigger:
    schedule: "0 22 * * *"
  restic:
    copyMethod: Snapshot
    pruneIntervalDays: 10
    repository: mealie-restic-secret
    retain:
      daily: 14
---
apiVersion: v1
kind: Secret
metadata:
  name: mealie-restic-secret
  namespace: default
type: Opaque
stringData:
  # The repository url
  RESTIC_REPOSITORY: s3:http://minio.storage.svc.cluster.local:9000/mealie
  # The repository encryption key
  RESTIC_PASSWORD: "${RESTIC_PW}"
  # ENV vars specific to the back end
  # https://restic.readthedocs.io/en/stable/030_preparing_a_new_repo.html
  AWS_ACCESS_KEY_ID: "${MINIO_USER}"
  AWS_SECRET_ACCESS_KEY: "${MINIO_PASSWORD}"
