---
apiVersion: v1
kind: ConfigMap
metadata:
  name: homepage-config
  namespace: home
  labels:
    app.kubernetes.io/name: homepage
  annotations:
    reloader.stakater.com/match: "true"
data:
  settings.yaml: |
    ---
    title: Dashboard
    favicon: https://raw.githubusercontent.com/ahgraber/homelab-gitops-k3s/main/cluster/apps/services/homepage/icons/favicon.png
    theme: dark
    color: neutral
    layout: # key by group name in services.yaml
      Infrastructure:
        # style: row
        # columns: 3
        # icon: home-assistant.png
        # headerStyle: boxed
      Monitoring:
        # style: row
        # columns: 3
        # icon: home-assistant.png
        # headerStyle: boxed
      Home:
        # style: row
        # columns: 4
        # icon: home-assistant.png
        # headerStyle: boxed
      Cloud:
        # style: row
        # columns: 3
        # icon: home-assistant.png
        # headerStyle: boxed
      Work:
        # style: row
        # columns: 3
        # icon: home-assistant.png
        # headerStyle: boxed
  widgets.yaml: |
    ---
    # - logo:
    - search:
        provider: custom
        url: https://search.unlocked.link/search?q=
        target: _blank
        # focus: true # Optional, will set focus to the search bar on page load
    - openmeteo:
        label: Home # optional
        latitude: 50.9096219 
        longitude: 6.8081935
        units: imperial # or metric
        cache: 5 # Time in minutes to cache API responses, to stay within limits
  services.yaml: |
    ---
    - Infrastructure:
        - Athena:
            href: https://athena.${SECRET_DOMAIN}
            icon: synology.png
            # description: Athena NAS
        - AdGuard:
            href: https://pihole${SECRET_DOMAIN}
            icon: pihole.png
            # description: Add-Blocking
            widget:
              type: pihole
              url: https://pihole.int.swalb.io
        - HomeAssistant:
            href: https://hass.${SECRET_DOMAIN}:8123
            icon: home-assistant-circle.png
            # description: This is my service
    - Monitoring:
        - Uptime-Kuma:
            href: https://uptime.${SECRET_DOMAIN}
            icon: uptime-kuma.png
            description: Uptime-Kuma dashboard
        - Grafana:
            href: https://grafana.${SECRET_DOMAIN}
            icon: grafana.png
            # description: Grafana Dashboard
        - Alertmanager:
            href: https://alertmanager.${SECRET_DOMAIN}
            icon: alertmanager.png
            # description: This is my service
        - Prometheus:
            href: https://prometheus.${SECRET_DOMAIN}
            icon: prometheus.png
            # description: This is my service
    - Storage:
        - Longhorn:
            href: https://longhorn.${SECRET_DOMAIN}
            icon: longhorn.png
        - MinIO:
            href: https://minio.${SECRET_DOMAIN}
            icon: minio.png
            # description: This is my service
    - Cloud:
        - Mail:
            href: https://longhorn.${SECRET_DOMAIN}
            icon: longhorn.png
        - Mailcow:
            href: https://minio.${SECRET_DOMAIN}
            icon: minio.png
            # description: This is my service
        - RSS:
            href: https://minio.${SECRET_DOMAIN}
            icon: minio.png
            # description: This is my service
        - Nextcloud:
            href: https://minio.${SECRET_DOMAIN}
            icon: minio.png
            # description: This is my service
        - Wiki:
            href: https://minio.${SECRET_DOMAIN}
            icon: minio.png
            # description: This is my service
        - KDVZ-Mail:
            href: https://minio.${SECRET_DOMAIN}
            icon: minio.png
            # description: This is my service
  bookmarks.yaml: |
    ---
        - Developer:
            - Github:
                - abbr: GH
                  href: https://github.com/

        - Social:
            - Reddit:
                - icon: reddit.png
                  href: https://reddit.com/
            - Twitter: 
                - icon: twitter.png
                  href: https://twitter.com

        - Entertainment:
            - YouTube:
                - abbr: YT
                  href: https://youtube.com/
  docker.yaml: |
    ---