---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app homepage
  namespace: hoem
spec:
  interval: 10m0s
  chart:
    spec:
      chart: homepage
      version: 1.0.0
      interval: 10m0s
      sourceRef:
        kind: HelmRepository
        name: jameswynn
        namespace: home

  values:
    image:
      repository: ghcr.io/jameswynn/homepage
      pullPolicy: IfNotPresent
      tag: kubernetes@sha256:aba1848045c44e13b74607d3bfcef016b1b9b5c954a46805c5937ab79c4ec918

    enableRbac: true
    config:
      kubernetes:
        mode: cluster
      settings:
        theme: dark
      widgets:
        - resources:
            backend: kubernetes
            expanded: true
            cpu: true
            memory: true
      bookmarks:
        - Infrastructure:
            - "Synology NAS":
                - abbr: SN
                  href: https://athena.${SECRET_DOMAIN}
                  icon: synology.png
      services:

    podAnnotations:
      configmap.reloader.stakater.com/reload: *app

    ingress:
      main:
        enabled: true
        ingressClassName: "nginx"
        annotations:
          gethomepage.dev/enabled: "true"
          gethomepage.dev/name: "Homepage"
          gethomepage.dev/description: "A modern, secure, highly customizable application dashboard."
          gethomepage.dev/group: Applications
          gethomepage.dev/icon: "homepage.png"
          cert-manager.io/cluster-issuer: "letsencrypt-production"  
        hosts:
          - host: &host "home.${SECRET_DOMAIN}"
            paths:
              - path: /

        tls:
          - hosts:
              - *host
            secretName: letsencrypt-homepage