---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: homepage
  namespace: home
spec:
  interval: 15m
  chart:
    spec:
      # renovate: registryUrl=https://bjw-s.github.io/helm-charts
      chart: app-template
      version: 1.2.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s-charts
        namespace: flux-system
  values:
    global:
      # nameOverride: homepage
      annotations:
        reloader.stakater.com/search: "true"

    image:
      repository: ghcr.io/benphelps/homepage
      tag: v0.5.9
      pullPolicy: IfNotPresent

    env:
      TZ: ${TIMEZONE}
      LOG_LEVEL: debug

    ingress:
      main:
        enabled: true
        ingressClassName: "nginx"
        annotations:
          cert-manager.io/cluster-issuer: "letsencrypt-production"
        hosts:
          - host: "home.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
        - hosts:
            - "home.${SECRET_DOMAIN}"
          secretName: "home.${SECRET_DOMAIN}"

    service:
      main:
        ports:
          http:
            port: 3000
            targetPort: 3000

    persistence:
      config:
        enabled: true
        # type: configmap
        # name: homepage-config
        # mountPath: /app/config
        type: custom
        volumeSpec:
          configMap:
            name: homepage-config
        subPath:
          - path: settings.yaml
            mountPath: /app/config/settings.yaml
          - path: widgets.yaml
            mountPath: /app/config/widgets.yaml
          - path: services.yaml
            mountPath: /app/config/services.yaml
          - path: bookmarks.yaml
            mountPath: /app/config/bookmarks.yaml
          - path: docker.yaml
            mountPath: /app/config/docker.yaml

    resources:
      requests:
        cpu: 25m
        memory: 105M
      limits:
        memory: 225M