---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: system-upgrade
resources:
  # renovate: datasource=docker image=rancher/system-upgrade-controller
  - ./namespace.yaml
  - ./system-upgrade-controller/app
  - ./system-upgrade-controller/plans