---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: vault
  namespace: security
  labels:
    kustomize.toolkit.fluxcd.io/prune: disabled
spec:
  interval: 6h
  chart:
    spec:
      chart: vault
      version: 0.25.0
      sourceRef:
        kind: HelmRepository
        name: hashicorp-charts
        namespace: flux-system
  values:
    global:
      enabled: false
    server:
      updateStrategyType: RollingUpdate
      enabled: true
      logFormat: "json"
      readinessProbe:
        enabled: true
        path: "/v1/sys/health?standbyok=true&sealedcode=204&uninitcode=204"
      ingress:
        enabled: true
        ingressClassName: internal
        hosts:
          - host: hashivault.${DOMAIN}
            paths:
              - /
        tls:
          - secretName: alb-home-tls
            hosts:
              - hashivault.${DOMAIN}
        standalone:
          enabled: true
          config: |
            log_format = "json"
            log_level = "debug"
            ui = true
            cluster_name = "alb-prod"
            storage "file" {
              path = "/vault/data"
            }
            # HTTPS listener
            listener "tcp" {
              address = "[::]:8200"
              cluster_address = "[::]:8201"
              tls_disable = 1
            }
            telemetry {
              prometheus_retention_time = "24h"
              disable_hostname = true
            }
