---
apiVersion: db.movetokube.com/v1alpha1
kind: Postgres
metadata:
  name: home-assistant-db
  namespace: default
spec:
  database: home-assistant
---
apiVersion: db.movetokube.com/v1alpha1
kind: PostgresUser
metadata:
  name: home-assistant-user
  namespace: default
spec:
  role: home-assistant
  database: home-assistant-db
  secretName: database
  privileges: OWNER
