---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: jellyseerr
  namespace: media
spec:
  chart:
    spec:
      chart: app-template
      version: 2.3.0
      interval: 15m
      sourceRef:
        kind: HelmRepository
        name: bjw-s-charts
        namespace: flux-system
  install:
    createNamespace: true
    remediation:
      retries: 5
  interval: 15m
  upgrade:
    remediation:
      retries: 5
  values:
    controllers:
      main:
        type: statefulset
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          main:
            image:
              repository: docker.io/fallenbagel/jellyseerr
              tag: preview-OIDC
            env:
              LOG_LEVEL: "info"
              PORT: &port 8080
            resources:
              requests:
                memory: 443M
              limits:
                memory: 536M
    service:
      main:
        ports:
          http:
            port: 8080
    ingress:
      main:
        enabled: true
        className: internal-nginx
        hosts:
          - host: &host jellyseer.${DOMAIN}
            paths:
              - path: /
                service:
                  name: main
                  port: http
        tls:
          - hosts:
              - "jellyseer.${DOMAIN}"
    persistence:
      data:
        enabled: true
        existingClaim: jellyseer-config
        globalMounts:
          - path: /app/config
