---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jellyseer-config
  namespace: media
  labels:
    app.kubernetes.io/name: &name jellyseer
    app.kubernetes.io/instance: *name
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: ceph-block
