---
apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: jellyseer
  namespace: media
spec:
  sourcePVC: jellyseer-config
  trigger:
    schedule: "0 22 * * *"
  restic:
    copyMethod: Snapshot
    pruneIntervalDays: 7
    volumeSnapshotClassName: csi-ceph-blockpool
    storageClassName: ceph-block
    cacheStorageClassName: local-hostpath
    cacheCapacity: 1Gi
    repository: jellyseer-restic
    retain:
      daily: 7
---
apiVersion: v1
kind: Secret
metadata:
  name: jellyseer-restic
  namespace: media
type: Opaque
stringData:
  # The repository url
  RESTIC_REPOSITORY: s3:http://192.168.178.35:9000/jellyseer
  # The repository encryption key
  RESTIC_PASSWORD: "${RESTIC_PW}"
  # ENV vars specific to the back end
  # https://restic.readthedocs.io/en/stable/030_preparing_a_new_repo.html
  AWS_ACCESS_KEY_ID: "${MINIO_USER}"
  AWS_SECRET_ACCESS_KEY: "${MINIO_PASSWORD}"
