---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: reloader
  namespace: system
spec:
  interval: 15m
  chart:
    spec:
      chart: reloader
      version: 1.0.62
      sourceRef:
        kind: HelmRepository
        name: stakater-charts
        namespace: flux-system
  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  values:
    reloader:
      podMonitor:
        enabled: true

      reloadStrategy: annotations

      deployment:
        resources:
          requests:
            cpu: 5m
            memory: 144Mi
          limits:
            memory: 256Mi
