apiVersion: v1
kind: Secret
metadata:
    name: cnpg-backup
    namespace: databases
    label:
        cnpg.io/reload: "true"
stringData:
    ACCESS_KEY_ID: ENC[AES256_GCM,data:tKyq+NtZhOE=,iv:WMH97w2yHRLIXzm3e4wmCfaBsT4KIx1sSTBQeOvypBY=,tag:DQ37ddXoVvr5AbkYxA6I7g==,type:str]
    ACCESS_SECRET_KEY: ENC[AES256_GCM,data:EOpZ0Ulwi+uJ+EI2aoNY9zheCPRL3DZPuDA=,iv:sk075EsRPuWeyeFsb6r0ke7AQ+zK4KBbWuD4Nbr7kM4=,tag:lsdXrXaVm6ZQS+OMnp04Zw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age14zezx8350dxxh9kpqhpcna7a3gsma24n63qppqy0vfq47vvfkatqry5e9q
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBobzh5QVpMd3FJQktUMFc0
            VHJlV3dpRXRFakZwWFVJMnRGY3VYckc2Rm5vCmtmbEo3S0lmSjZmK1NLTHY2aDBE
            WXlyeVBKVHE0dFFCUHdNQzd0QXFwZmsKLS0tIHdmNURyQURFL04yWFdmMFpZRm9w
            TG9YT2lLR0c0UlhCcm41TGpRWTFzYVEKY1+OD/VUm9FkkWE7eFsopzC/mPua0asN
            RFYRyFzGgKzuYysCu+TtC0fIUN6GMnnfr1xEwBO9Ir+U9M9tnyIP6A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-05-14T14:07:45Z"
    mac: ENC[AES256_GCM,data:M0j1N74axzTa9W3IN+kAR6wvISftOsbFxSLgsvJp8UP+LLrGl37kBzLisMsIXYckeOV2A+rmJ2BlO9DoNVXibXvzUVCtH8bhYrYHEDhJhSx0tYCTY9I0qPDO1goHjNFWAQ3v4Ln/DIJEtyliRjh+lxCx2ZHP+FJWk0r+ypRwWvU=,iv:LQyn6gTruxdHiBJCfw/UFWhA1A5SzbW3/QN3Tl0sMTU=,tag:LAZ/uBgdywBGmf/tmasTzQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
