apiVersion: v1
kind: Secret
metadata:
    name: cnpg-backup
    namespace: databases
    label:
        cnpg.io/reload: "true"
stringData:
    ACCESS_KEY_ID: ENC[AES256_GCM,data:tWdQIsfdWBW6WWbnZrDxkQ==,iv:mBxdekdw6sSDS3tsmwvK+87VAo3f+MQDpw2R+8bQ3Rk=,tag:5MsGIEWaHqjuMMAQRh8FEw==,type:str]
    ACCESS_SECRET_KEY: ENC[AES256_GCM,data:l/3KEYpQ2kBa6fUQGfCLKn8l4GKJHhTUDPZOWwHDti0=,iv:7/W4hvqP+Fa/pe0oDD0Xhp8ZWZ/fZbQXXR8ATH00rkU=,tag:ZnsxM/HEifp/C8EhklXPoQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age14zezx8350dxxh9kpqhpcna7a3gsma24n63qppqy0vfq47vvfkatqry5e9q
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBobzh5QVpMd3FJQktUMFc0
            VHJlV3dpRXRFakZwWFVJMnRGY3VYckc2Rm5vCmtmbEo3S0lmSjZmK1NLTHY2aDBE
            WXlyeVBKVHE0dFFCUHdNQzd0QXFwZmsKLS0tIHdmNURyQURFL04yWFdmMFpZRm9w
            TG9YT2lLR0c0UlhCcm41TGpRWTFzYVEKY1+OD/VUm9FkkWE7eFsopzC/mPua0asN
            RFYRyFzGgKzuYysCu+TtC0fIUN6GMnnfr1xEwBO9Ir+U9M9tnyIP6A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-05-14T13:08:34Z"
    mac: ENC[AES256_GCM,data:30YfBVUcHFckIJySE8ZdiYYMRsZqaEaT88Si5gDfoJThZm5m1fepQ5NnYUOaYlJFvVxMnmbPUDr0hRX1Q9MfHafNmj5eV5mvFHax9hZPUXErdGwSyMsfC4yHhUjxL9WJYzCDgvxfIm6/b6jW354Z6AjK6rYqLqVktnhe/5fDUQs=,iv:jP9KSHaxbBB9SFMmRVFkcpTppYsIxQV+SpNC4FSpSYI=,tag:7sO8FZKfnGdly1HWpt8bBQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
