apiVersion: v1
kind: Secret
metadata:
    name: cnpg-backup
    namespace: databases
    label:
        cnpg.io/reload: "true"
stringData:
    ACCESS_KEY_ID: "${CK_ACCESS_KEY}"
    ACCESS_SECRET_KEY: "${CK_SECRET_KEY}"
---
apiVersion: v1
kind: Secret
#type: kubernetes.io/basic-auth
metadata:
    name: cloudnative-pg
    namespace: databases
stringData:
    username: "${PG_CLUSTER_USER}"
    password: "${PG_CLUSTER_PW}"
