apiVersion: v1
kind: Secret
metadata:
    name: cnpg-backup
    namespace: databases
    label:
        cnpg.io/reload: "true"
stringData:
    ACCESS_KEY_ID: ENC[AES256_GCM,data:wJhbTQiNlif4tDVLpXUVUg==,iv:wsQ5PBM6q0pHZ+fd/6K2s8cCIMToE5UYvOZtboQdb2o=,tag:yHF37TuOgSpNRhmqND1kHA==,type:str]
    ACCESS_SECRET_KEY: ENC[AES256_GCM,data:BZ2F2rf8n47cU22nZxzvPci5gQlzwVOYCNfRwT97Q9k=,iv:HbvCqGZfiqFjm7pytERbSjEp8WhjifJoxwq7d++lPUM=,tag:YYQ5jhC4A+AueGIFA7wGvw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age14zezx8350dxxh9kpqhpcna7a3gsma24n63qppqy0vfq47vvfkatqry5e9q
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3Z0pwRzRaV1VibWU1WGJT
            SEZJeE1TaHhvWW5QbUk4SmhyNlZTMWw0T1JzCnRLck1iMDg3UDQ5bEN4empSemZR
            TWp4c3dYOFE0eXJYQ2lGSXUvVGxmdmsKLS0tIE0rUHRxaEhUYnVBaWNQeFhhMk8r
            RkM3OEQrVDNuRXdOZnNsRStUcUp3YXMKBf0tFT92FP+EX0rb29IRRURPWVcQnZeb
            Wny+nI/qSwRiGrU1YKDITJwR1pEnBm8mFw5xVzXDL3KKoYkhol0r8A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-05-15T19:52:25Z"
    mac: ENC[AES256_GCM,data:GBB/eCEG/68/N8SPrLbH8P4Angct4QY0FlcajcBJv55HCJMI3TRmtD3oOKiowcH4Xy7jpv7FZrOc7pqnT81TzSm641Z3IRmdHQqSrO8PR/xxSztRgT/Oom/A9S1bcghZUcDzrBbfcW4JD5IO3OY4Ii+p+8qu8pG8GHWFhyazVDs=,iv:wz90QF1cTqUp3BcjDoA/im5oXCpq3Q4TAkNZRqKaewE=,tag:K0Gjthlt5t6zgKzkcwSlig==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
---
apiVersion: v1
kind: Secret
#type: kubernetes.io/basic-auth
metadata:
    name: cloudnative-pg
    namespace: databases
stringData:
    username: ENC[AES256_GCM,data:snVROAhShQ==,iv:/uWbuZ9Ws4y1PH+NeDlC6Kyvs0xe3zUscaFS22SIcAc=,tag:GWbS82qKhfADVW6TfOD9aQ==,type:str]
    password: ENC[AES256_GCM,data:+W/v67MoSVayI3msl0hheL01DN6Rmo05lbX5yTELVID8,iv:ez7GBON3oBL7UQHdpy4Zkccy8IfXBhrEf8gn+Gn8LYo=,tag:FpXmgcyujKR1KuDqKvlqzw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age14zezx8350dxxh9kpqhpcna7a3gsma24n63qppqy0vfq47vvfkatqry5e9q
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3Z0pwRzRaV1VibWU1WGJT
            SEZJeE1TaHhvWW5QbUk4SmhyNlZTMWw0T1JzCnRLck1iMDg3UDQ5bEN4empSemZR
            TWp4c3dYOFE0eXJYQ2lGSXUvVGxmdmsKLS0tIE0rUHRxaEhUYnVBaWNQeFhhMk8r
            RkM3OEQrVDNuRXdOZnNsRStUcUp3YXMKBf0tFT92FP+EX0rb29IRRURPWVcQnZeb
            Wny+nI/qSwRiGrU1YKDITJwR1pEnBm8mFw5xVzXDL3KKoYkhol0r8A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-05-15T19:52:25Z"
    mac: ENC[AES256_GCM,data:GBB/eCEG/68/N8SPrLbH8P4Angct4QY0FlcajcBJv55HCJMI3TRmtD3oOKiowcH4Xy7jpv7FZrOc7pqnT81TzSm641Z3IRmdHQqSrO8PR/xxSztRgT/Oom/A9S1bcghZUcDzrBbfcW4JD5IO3OY4Ii+p+8qu8pG8GHWFhyazVDs=,iv:wz90QF1cTqUp3BcjDoA/im5oXCpq3Q4TAkNZRqKaewE=,tag:K0Gjthlt5t6zgKzkcwSlig==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
