---
apiVersion: v1
kind: Service
metadata:
  name: &app postgres
  namespace: databases
  labels:
    app.kubernetes.io/name: *app
    app.kubernetes.io/instance: *app
  annotations:
    external-dns.alpha.kubernetes.io/hostname: postgres.${DOMAIN}
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  loadBalancerIP: "${POSTGRES_LB}"
  ports:
    - name: postgres
      port: 5432
      protocol: TCP
      targetPort: 5432
  selector:
    cnpg.io/cluster: alb-v1
    role: primary
