---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: planka-data
  namespace: selfhosted
  labels:
    app.kubernetes.io/name: &name planka
    app.kubernetes.io/instance: *name
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: ceph-block
