apiVersion: v1
kind: Secret
metadata:
    name: planka-secret
    namespace: selfhosted
stringData:
    database: ENC[AES256_GCM,data:0RcfsOFh,iv:MyxegR8xncC+EILrgJRpEcC5BLInSdALKN3uAhim55E=,tag:5HMwBnBvHfniu2GShBeL7g==,type:str]
    username: ENC[AES256_GCM,data:pnVj6Uz5,iv:vA8IryxBgS6rDH1HfnPEbeqXv5Dl5h0+aXJU3//MlzI=,tag:QUVMLIy5g+Ml11hhZb/tdg==,type:str]
    password: ENC[AES256_GCM,data:AjJoO+EhnDSF2Qy895TK6jlRHhc=,iv:t4OGt5Y2Dv6S/qVyR3Pcn3/gHV4O8QDFAE8P8eYW89o=,tag:V0cSZadrq9aqCZNJsnMLBA==,type:str]
    postgresPassword: ENC[AES256_GCM,data:zkC2lzWMmkxVDiCvTtZnj9s=,iv:1zBkSQod9/HuYv6FMuZoxxoneQwYE10CLOhGalMQTEM=,tag:/O/apiBgXYHR7jwybDnXDA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age14zezx8350dxxh9kpqhpcna7a3gsma24n63qppqy0vfq47vvfkatqry5e9q
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6LzdWZjExbWVWMWN2MHpa
            UnBPZmlIUTZnaDNQNG5nZk5mRWszRStNUXdJCldkazlROXdqQ3ljRmYzS1JsUFRP
            UHNTTG0yZzQwUEpTaFIzV3lWSlF0VWsKLS0tIHB0aTRiZUdIN2FoWDR5QWU1aVJ0
            V2hYeWxsaUJBY3hobVZ4NHYrNk01cXcKxUUi34R9bETWWuzSZEYBUySb7Aap4486
            2NVUzmA2LY14akE/pdHwsrZUgTdy5943EI7hvg2s2YyV5SCAqvLnpg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-12-20T22:09:30Z"
    mac: ENC[AES256_GCM,data:Y6A/UtiVloM1Sfitf8M8y6dzB+6MjE1zmJUb2wujAfk16Q9XbxWvGYsscicmp/cSG0oyFRFlHMervHFuX9RsR8wtMEB0A7B2kMHjD43unReh3Jy9yG9ITzIKa/xlNTZEkdkCPgb9c+RRjA7R4QneGfw7lMpcbmb1O7Vvu054xrk=,iv:+wuau2jGre4GnrPf+OOTdHbm5KzIXso2Lp2htqzj0JU=,tag:+rwgrsba7GpkIxwXzvhxKw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
