---
- name: System Configuration (2) | Disable swap at runtime
  command: "swapoff -a"
  when: ansible_swaptotal_mb > 0

- name: System Configuration (2) | Disable swap on boot
  ansible.posix.mount:
    name: "{{ item }}"
    fstype: swap
    state: absent
  loop:
    - swap
    - none
- name: "Configure SSH for Public Key Authentication."
  shell: |
    sudo sed -i 's/.*PermitRootLogin.*/PermitRootLogin no/' /etc/ssh/sshd_config
    sudo sed -i 's/.*PubkeyAuthentication.*/PubkeyAuthentication yes/' /etc/ssh/sshd_config
- name: "Restarting the SSH daemon."
  shell: |
    sudo systemctl restart sshd
- name: "Set Timezone"
  shell: |
    sudo timedatectl set-timezone Europe/Berlin

- name: Set a hostname
  ansible.builtin.hostname:
    name: "{{ inventory_hostname}}"
