---
apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: jellyfin-restic
  namespace: home
spec:
  sourcePVC: jellyfin-config-v1
  trigger:
    schedule: "0 0 * * *"
  restic:
    pruneIntervalDays: 15
    repository: jellyfin-restic
    retain:
      hourly: 1
      daily: 1
      weekly: 1
      monthly: 1
      yearly: 1
    copyMethod: Clone