---
apiVersion: volsync.backube/v1alpha1
kind: ReplicationDestination
metadata:
  name: jellyfin
  namespace: media
spec:
  trigger:
    manual: restore-once
  restic:
    repository: jellyfin-restic
    destinationPVC: config-jellyfin-0
    copyMethod: Direct
    storageClassName: ceph-block
    previous: 4
    moverSecurityContext:
      runAsUser: 0
      runAsGroup: 0
      fsGroup: 0
