---
apiVersion: volsync.backube/v1alpha1
kind: ReplicationDestination
metadata:
  name: zigbee2mqtt-config-v1
  namespace: default
spec:
  trigger:
    manual: restore-once
  restic:
    repository: zigbee2mqtt-restic
    destinationPVC: zigbee2mqtt-config-v1
    copyMethod: Direct
    storageClassName: ceph-block
    # IMPORTANT NOTE:
    #   Set to the last X number of snapshots to restore from
    previous: 3
    moverSecurityContext:
      runAsUser: 0
      runAsGroup: 0
      fsGroup: 0
