
---
apiVersion: volsync.backube/v1alpha1
kind: ReplicationDestination
metadata:
  name: config-home-assistant-0
  namespace: default
spec:
  trigger:
    manual: restore-once
  restic:
    repository: hass-restic-secret
    destinationPVC: config-home-assistant-0
    copyMethod: Direct
    storageClassName: ceph-block
    # IMPORTANT NOTE:
    #   Set to the last X number of snapshots to restore from
    previous: 2