---
apiVersion: volsync.backube/v1alpha1
kind: ReplicationDestination
metadata:
  name: uptime-kuma-backup-v2
  namespace: monitoring
spec:
  trigger:
    manual: restore-once
  restic:
    repository: uptime-kuma-restic-secret
    destinationPVC: uptime-kuma-v1
    copyMethod: Direct
    storageClassName: ceph-block
    # IMPORTANT NOTE:
    #   Set to the last X number of snapshots to restore from
    previous: 3
    moverSecurityContext:
      runAsUser: 0
      runAsGroup: 0
      fsGroup: 0
