
---
apiVersion: volsync.backube/v1alpha1
kind: ReplicationDestination
metadata:
  name: paperless-ngx-data
  namespace: default
spec:
  trigger:
    manual: restore-once
  restic:
    repository: paperless-restic
    destinationPVC: paperless-ngx-data
    copyMethod: Direct
    storageClassName: ceph-block
    # IMPORTANT NOTE:
    #   Set to the last X number of snapshots to restore from
    previous: 2
    moverSecurityContext:
      runAsUser: 0
      runAsGroup: 0
      fsGroup: 0