---
apiVersion: volsync.backube/v1alpha1
kind: ReplicationDestination
metadata:
  name: lldap-backup
  namespace: identity
spec:
  trigger:
    manual: restore-once
  restic:
    repository: lldap-restic-secret
    destinationPVC: lldap-data
    copyMethod: Direct
    storageClassName: ceph-block
    # IMPORTANT NOTE:
    #   Set to the last X number of snapshots to restore from
    previous: 6
    moverSecurityContext:
      runAsUser: 1000
      runAsGroup: 1000
      fsGroup: 1000
