---
apiVersion: volsync.backube/v1alpha1
kind: ReplicationDestination
metadata:
  name: freshrss-backup
  namespace: default
spec:
  trigger:
    manual: restore-once
  restic:
    repository: freshrss-restic-secret
    destinationPVC: freshrss-config-v1
    copyMethod: Direct
    storageClassName: ceph-block
    # IMPORTANT NOTE:
    #   Set to the last X number of snapshots to restore from
    previous: 3
    moverSecurityContext:
      runAsUser: 0
      runAsGroup: 33
      fsGroup: 33
