---
apiVersion: volsync.backube/v1alpha1
kind: ReplicationDestination
metadata:
  name: authelia-backup
  namespace: identity
spec:
  trigger:
    manual: restore-once
  restic:
    repository: authelia-restic-secret
    destinationPVC: authelia-data
    copyMethod: Direct
    storageClassName: ceph-block
    # IMPORTANT NOTE:
    #   Set to the last X number of snapshots to restore from
    previous: 2
