
---
apiVersion: volsync.backube/v1alpha1
kind: ReplicationDestination
metadata:
  name: uptime-kuma-restic
  namespace: default
spec:
  trigger:
    manual: restore-once
  restic:
    repository: uptime-kuma-restic
    destinationPVC: uptime-kuma-restic
    copyMethod: Direct
    storageClassName: ceph-block
    # IMPORTANT NOTE:
    #   Set to the last X number of snapshots to restore from
    previous: 2