---
apiVersion: volsync.backube/v1alpha1
kind: ReplicationDestination
metadata:
  name: vaultwarden-v3
  namespace: default
spec:
  trigger:
    manual: restore-once
  restic:
    repository: vaultwarden-restic-secret
    destinationPVC: vaultwarden-v1
    copyMethod: Direct
    storageClassName: ceph-block
    # IMPORTANT NOTE:
    #   Set to the last X number of snapshots to restore from
    previous: 6
    moverSecurityContext:
      runAsUser: 0
      runAsGroup: 0
      fsGroup: 0
